/*
 * Product communication configuration.
 *
 * UART1 line coding is generated by Config Tools in board/peripherals.c.
 * Changing PRODUCT_MODBUS_FC1_PROTOCOL selects the parser only; keep the
 * Wizard UART configuration consistent with the connected Modbus master.
 */

#ifndef PRODUCT_CONFIG_H_
#define PRODUCT_CONFIG_H_

#define PRODUCT_MODBUS_PROTOCOL_RTU   (1U)
#define PRODUCT_MODBUS_PROTOCOL_ASCII (2U)

#ifndef PRODUCT_MODBUS_FC1_ENABLE
#define PRODUCT_MODBUS_FC1_ENABLE (1U)
#endif

#ifndef PRODUCT_MODBUS_FC1_PROTOCOL
#define PRODUCT_MODBUS_FC1_PROTOCOL PRODUCT_MODBUS_PROTOCOL_RTU
#endif

#ifndef PRODUCT_MODBUS_FC1_UNIT_ADDRESS
#define PRODUCT_MODBUS_FC1_UNIT_ADDRESS (2U)
#endif

#ifndef PRODUCT_MODBUS_FC1_FRAME_TIMEOUT_US
#if (PRODUCT_MODBUS_FC1_PROTOCOL == PRODUCT_MODBUS_PROTOCOL_ASCII)
/* ASCII ends at CRLF; this is only the maximum inter-character guard time. */
#define PRODUCT_MODBUS_FC1_FRAME_TIMEOUT_US (1000000U)
#else
/* Modbus Serial Line recommendation above 19200 baud. */
#define PRODUCT_MODBUS_FC1_FRAME_TIMEOUT_US (1750U)
#endif
#endif

#if ((PRODUCT_MODBUS_FC1_ENABLE != 0U) && (PRODUCT_MODBUS_FC1_ENABLE != 1U))
#error "PRODUCT_MODBUS_FC1_ENABLE must be 0 or 1"
#endif

#if ((PRODUCT_MODBUS_FC1_PROTOCOL != PRODUCT_MODBUS_PROTOCOL_RTU) && \
     (PRODUCT_MODBUS_FC1_PROTOCOL != PRODUCT_MODBUS_PROTOCOL_ASCII))
#error "PRODUCT_MODBUS_FC1_PROTOCOL must select RTU or ASCII"
#endif

#if ((PRODUCT_MODBUS_FC1_UNIT_ADDRESS < 1U) || \
     (PRODUCT_MODBUS_FC1_UNIT_ADDRESS > 247U))
#error "PRODUCT_MODBUS_FC1_UNIT_ADDRESS must be 1..247"
#endif

#if (PRODUCT_MODBUS_FC1_FRAME_TIMEOUT_US == 0U)
#error "PRODUCT_MODBUS_FC1_FRAME_TIMEOUT_US must be greater than zero"
#endif

#endif /* PRODUCT_CONFIG_H_ */
