#ifndef PRODUCT_INTERNAL_ADC_CONFIG_H
#define PRODUCT_INTERNAL_ADC_CONFIG_H

/*
 * LPC55S16 LPADC uses kLPADC_ReferenceVoltageAlt3, which selects the
 * board's external 2.5 V VREFP source.
 */
#define PRODUCT_INTERNAL_ADC_REFERENCE_UV            (2500000UL)
#define PRODUCT_INTERNAL_ADC_FULL_SCALE_CODE         (65535UL)

/* TMP20: VOUT = -11.77 mV/degree C * T + 1.8605 V. */
#define PRODUCT_TMP20_ZERO_DEGREE_UV                 (1860500L)
#define PRODUCT_TMP20_SLOPE_UV_PER_DEGREE            (11770L)
#define PRODUCT_TMP20_MIN_TEMPERATURE_CENTI_C        (-2000L)
#define PRODUCT_TMP20_MAX_TEMPERATURE_CENTI_C        (8500L)

#define PRODUCT_CJC_SAMPLE_PERIOD_MS                 (100U)
#define PRODUCT_MCU_TEMPERATURE_SAMPLE_PERIOD_MS     (1000U)
#define PRODUCT_MCU_OVERTEMPERATURE_CENTI_C          (8500L)
#define PRODUCT_MCU_OVERTEMPERATURE_CONFIRM_COUNT    (3U)

#endif /* PRODUCT_INTERNAL_ADC_CONFIG_H */
