/*
 * Product communication configuration.
 *
 * UART1 line coding is generated by Config Tools in board/peripherals.c.
 * RTU timing is derived from that live configuration unless both override
 * values below are non-zero. Pin assignments are not controlled here.
 */

#ifndef PRODUCT_CONFIG_H_
#define PRODUCT_CONFIG_H_

#define PRODUCT_MODBUS_PROTOCOL_RTU   (1U)
#define PRODUCT_MODBUS_PROTOCOL_ASCII (2U)

#ifndef PRODUCT_MODBUS_FC1_ENABLE
#define PRODUCT_MODBUS_FC1_ENABLE (1U)
#endif

#ifndef PRODUCT_MODBUS_FC1_PROTOCOL
#define PRODUCT_MODBUS_FC1_PROTOCOL PRODUCT_MODBUS_PROTOCOL_RTU
#endif

#ifndef PRODUCT_MODBUS_FC1_UNIT_ADDRESS
#define PRODUCT_MODBUS_FC1_UNIT_ADDRESS (2U)
#endif

#ifndef PRODUCT_MODBUS_FC1_FRAME_TIMEOUT_US
/* ASCII normally ends at CRLF; this is its maximum inter-character guard. */
#define PRODUCT_MODBUS_FC1_FRAME_TIMEOUT_US (1000000U)
#endif

/*
 * Leave both at zero to calculate from UART1 baud/data/parity/stop bits.
 * Above 19200 baud the Modbus recommendation is 750 us / 1750 us.
 */
#ifndef PRODUCT_MODBUS_FC1_RTU_T15_US
#define PRODUCT_MODBUS_FC1_RTU_T15_US (0U)
#endif

#ifndef PRODUCT_MODBUS_FC1_RTU_T35_US
#define PRODUCT_MODBUS_FC1_RTU_T35_US (0U)
#endif

/*
 * Extra delay between a valid request and assertion of the RS-485 TX direction.
 * Zero sends immediately. Set, for example, to 1000U for a 1 ms delay.
 */
#ifndef PRODUCT_MODBUS_FC1_TURNAROUND_DELAY_US
#define PRODUCT_MODBUS_FC1_TURNAROUND_DELAY_US (0U)
#endif

#if ((PRODUCT_MODBUS_FC1_ENABLE != 0U) && (PRODUCT_MODBUS_FC1_ENABLE != 1U))
#error "PRODUCT_MODBUS_FC1_ENABLE must be 0 or 1"
#endif

#if ((PRODUCT_MODBUS_FC1_PROTOCOL != PRODUCT_MODBUS_PROTOCOL_RTU) && \
     (PRODUCT_MODBUS_FC1_PROTOCOL != PRODUCT_MODBUS_PROTOCOL_ASCII))
#error "PRODUCT_MODBUS_FC1_PROTOCOL must select RTU or ASCII"
#endif

#if ((PRODUCT_MODBUS_FC1_UNIT_ADDRESS < 1U) || \
     (PRODUCT_MODBUS_FC1_UNIT_ADDRESS > 247U))
#error "PRODUCT_MODBUS_FC1_UNIT_ADDRESS must be 1..247"
#endif

#if (PRODUCT_MODBUS_FC1_FRAME_TIMEOUT_US == 0U)
#error "PRODUCT_MODBUS_FC1_FRAME_TIMEOUT_US must be greater than zero"
#endif

#if (((PRODUCT_MODBUS_FC1_RTU_T15_US == 0U) && \
      (PRODUCT_MODBUS_FC1_RTU_T35_US != 0U)) || \
     ((PRODUCT_MODBUS_FC1_RTU_T15_US != 0U) && \
      (PRODUCT_MODBUS_FC1_RTU_T35_US == 0U)))
#error "RTU T1.5 and T3.5 overrides must both be zero or both be non-zero"
#endif

#if ((PRODUCT_MODBUS_FC1_RTU_T15_US != 0U) && \
     (PRODUCT_MODBUS_FC1_RTU_T35_US <= PRODUCT_MODBUS_FC1_RTU_T15_US))
#error "RTU T3.5 must be greater than T1.5"
#endif

#endif /* PRODUCT_CONFIG_H_ */
