/*
 * FC0 is the external Modbus Slave and shares its pins with the boot and
 * maintenance debug console. No unsolicited debug text may be emitted after
 * communication starts. FC1 is the Modbus Master. Both ports use the same
 * line format and protocol.
 */
#ifndef PRODUCT_CONFIG_H_
#define PRODUCT_CONFIG_H_

#define PRODUCT_MODBUS_PROTOCOL_RTU   (1U)
#define PRODUCT_MODBUS_PROTOCOL_ASCII (2U)

/* Product and compatibility versions exposed through 0x2000..0x2008. */
#ifndef PRODUCT_FIRMWARE_VERSION_U16
#define PRODUCT_FIRMWARE_VERSION_U16 (1U)
#endif

#ifndef PRODUCT_FIRMWARE_VERSION_SUB1_U16
#define PRODUCT_FIRMWARE_VERSION_SUB1_U16 (0U)
#endif

#ifndef PRODUCT_FIRMWARE_VERSION_SUB2_U16
#define PRODUCT_FIRMWARE_VERSION_SUB2_U16 (0U)
#endif

#ifndef PRODUCT_COMPATIBLE_FIRMWARE_VERSION_MIN_U16
#define PRODUCT_COMPATIBLE_FIRMWARE_VERSION_MIN_U16 (1U)
#endif

#ifndef PRODUCT_COMPATIBLE_FIRMWARE_VERSION_MAX_U16
#define PRODUCT_COMPATIBLE_FIRMWARE_VERSION_MAX_U16 (1U)
#endif

#ifndef PRODUCT_COMPATIBLE_PARAMETER_VERSION_MIN_U16
#define PRODUCT_COMPATIBLE_PARAMETER_VERSION_MIN_U16 (1U)
#endif

#ifndef PRODUCT_COMPATIBLE_PARAMETER_VERSION_MAX_U16
#define PRODUCT_COMPATIBLE_PARAMETER_VERSION_MAX_U16 (1U)
#endif

#ifndef PRODUCT_COMPATIBLE_SOFTWARE_VERSION_MIN_U16
#define PRODUCT_COMPATIBLE_SOFTWARE_VERSION_MIN_U16 (1U)
#endif

#ifndef PRODUCT_COMPATIBLE_SOFTWARE_VERSION_MAX_U16
#define PRODUCT_COMPATIBLE_SOFTWARE_VERSION_MAX_U16 (1U)
#endif

#if ((PRODUCT_FIRMWARE_VERSION_U16 > 0xFFFFU) || \
     (PRODUCT_FIRMWARE_VERSION_SUB1_U16 > 0xFFFFU) || \
     (PRODUCT_FIRMWARE_VERSION_SUB2_U16 > 0xFFFFU) || \
     (PRODUCT_COMPATIBLE_FIRMWARE_VERSION_MIN_U16 > 0xFFFFU) || \
     (PRODUCT_COMPATIBLE_FIRMWARE_VERSION_MAX_U16 > 0xFFFFU) || \
     (PRODUCT_COMPATIBLE_PARAMETER_VERSION_MIN_U16 > 0xFFFFU) || \
     (PRODUCT_COMPATIBLE_PARAMETER_VERSION_MAX_U16 > 0xFFFFU) || \
     (PRODUCT_COMPATIBLE_SOFTWARE_VERSION_MIN_U16 > 0xFFFFU) || \
     (PRODUCT_COMPATIBLE_SOFTWARE_VERSION_MAX_U16 > 0xFFFFU))
#error "Product version values must fit in U16 registers"
#endif

#if (PRODUCT_COMPATIBLE_FIRMWARE_VERSION_MIN_U16 > \
     PRODUCT_COMPATIBLE_FIRMWARE_VERSION_MAX_U16)
#error "Compatible firmware version minimum exceeds maximum"
#endif

#if (PRODUCT_COMPATIBLE_PARAMETER_VERSION_MIN_U16 > \
     PRODUCT_COMPATIBLE_PARAMETER_VERSION_MAX_U16)
#error "Compatible parameter version minimum exceeds maximum"
#endif

#if (PRODUCT_COMPATIBLE_SOFTWARE_VERSION_MIN_U16 > \
     PRODUCT_COMPATIBLE_SOFTWARE_VERSION_MAX_U16)
#error "Compatible software version minimum exceeds maximum"
#endif

#ifndef PRODUCT_MODBUS_PROTOCOL
#define PRODUCT_MODBUS_PROTOCOL PRODUCT_MODBUS_PROTOCOL_RTU
#endif
#ifndef PRODUCT_MODBUS_BAUD_RATE
#define PRODUCT_MODBUS_BAUD_RATE (115200UL)
#endif
#ifndef PRODUCT_MODBUS_DATA_BITS
#define PRODUCT_MODBUS_DATA_BITS (8U)
#endif
/* 0=None, 1=Even, 2=Odd; values match HalSerialParity_t. */
#ifndef PRODUCT_MODBUS_PARITY
#define PRODUCT_MODBUS_PARITY (0U)
#endif
#ifndef PRODUCT_MODBUS_STOP_BITS
#define PRODUCT_MODBUS_STOP_BITS (1U)
#endif
#ifndef PRODUCT_MODBUS_FC0_UNIT_ADDRESS
#define PRODUCT_MODBUS_FC0_UNIT_ADDRESS (2U)
#endif
#ifndef PRODUCT_MODBUS_FC1_LOCAL_UNIT_ADDRESS
#define PRODUCT_MODBUS_FC1_LOCAL_UNIT_ADDRESS (1U)
#endif
#ifndef PRODUCT_MODBUS_FRAME_TIMEOUT_US
#define PRODUCT_MODBUS_FRAME_TIMEOUT_US (1000000UL)
#endif
/* Leave both at zero to derive RTU timing from the active line format. */
#ifndef PRODUCT_MODBUS_RTU_T15_US
#define PRODUCT_MODBUS_RTU_T15_US (0UL)
#endif
#ifndef PRODUCT_MODBUS_RTU_T35_US
#define PRODUCT_MODBUS_RTU_T35_US (0UL)
#endif
#ifndef PRODUCT_MODBUS_FC0_RESPONSE_DELAY_US
#define PRODUCT_MODBUS_FC0_RESPONSE_DELAY_US (0UL)
#endif
#ifndef PRODUCT_MODBUS_RESPONSE_TIMEOUT_MS
#define PRODUCT_MODBUS_RESPONSE_TIMEOUT_MS (1000UL)
#endif
#ifndef PRODUCT_MODBUS_APPLY_RESPONSE_TIMEOUT_MS
#define PRODUCT_MODBUS_APPLY_RESPONSE_TIMEOUT_MS (1000UL)
#endif
#ifndef PRODUCT_RS485_DE_ASSERT_DELAY_BITS
#define PRODUCT_RS485_DE_ASSERT_DELAY_BITS (1UL)
#endif
#ifndef PRODUCT_RS485_DE_RELEASE_DELAY_BITS
#define PRODUCT_RS485_DE_RELEASE_DELAY_BITS (1UL)
#endif

#if ((PRODUCT_MODBUS_PROTOCOL != PRODUCT_MODBUS_PROTOCOL_RTU) && \
     (PRODUCT_MODBUS_PROTOCOL != PRODUCT_MODBUS_PROTOCOL_ASCII))
#error "PRODUCT_MODBUS_PROTOCOL must select RTU or ASCII"
#endif
#if ((PRODUCT_MODBUS_BAUD_RATE != 4800UL) && \
     (PRODUCT_MODBUS_BAUD_RATE != 9600UL) && \
     (PRODUCT_MODBUS_BAUD_RATE != 19200UL) && \
     (PRODUCT_MODBUS_BAUD_RATE != 38400UL) && \
     (PRODUCT_MODBUS_BAUD_RATE != 57600UL) && \
     (PRODUCT_MODBUS_BAUD_RATE != 115200UL) && \
     (PRODUCT_MODBUS_BAUD_RATE != 230400UL))
#error "Unsupported PRODUCT_MODBUS_BAUD_RATE"
#endif
#if ((PRODUCT_MODBUS_DATA_BITS != 7U) && (PRODUCT_MODBUS_DATA_BITS != 8U))
#error "PRODUCT_MODBUS_DATA_BITS must be 7 or 8"
#endif
#if (PRODUCT_MODBUS_PARITY > 2U)
#error "PRODUCT_MODBUS_PARITY must be None, Even or Odd"
#endif
#if ((PRODUCT_MODBUS_STOP_BITS != 1U) && (PRODUCT_MODBUS_STOP_BITS != 2U))
#error "PRODUCT_MODBUS_STOP_BITS must be 1 or 2"
#endif
#if ((PRODUCT_MODBUS_PROTOCOL == PRODUCT_MODBUS_PROTOCOL_RTU) && \
     (PRODUCT_MODBUS_DATA_BITS != 8U))
#error "Modbus RTU requires 8 data bits"
#endif
#if ((PRODUCT_MODBUS_FC0_UNIT_ADDRESS < 1U) || \
     (PRODUCT_MODBUS_FC0_UNIT_ADDRESS > 247U))
#error "PRODUCT_MODBUS_FC0_UNIT_ADDRESS must be 1..247"
#endif
#if (((PRODUCT_MODBUS_RTU_T15_US == 0UL) && \
      (PRODUCT_MODBUS_RTU_T35_US != 0UL)) || \
     ((PRODUCT_MODBUS_RTU_T15_US != 0UL) && \
      (PRODUCT_MODBUS_RTU_T35_US == 0UL)))
#error "RTU T1.5 and T3.5 overrides must both be zero or non-zero"
#endif
#if ((PRODUCT_MODBUS_RTU_T15_US != 0UL) && \
     (PRODUCT_MODBUS_RTU_T35_US <= PRODUCT_MODBUS_RTU_T15_US))
#error "RTU T3.5 must be greater than T1.5"
#endif

#endif /* PRODUCT_CONFIG_H_ */
