/*
 * Copyright 2026
 * SPDX-License-Identifier: BSD-3-Clause
 */

#include "l02_rs485_dma.h"

#include "ProductFeatureConfig.h"
#include "fsl_ctimer.h"
#include "fsl_usart.h"
#include "fsl_usart_dma.h"
#include "peripherals.h"

typedef enum _l02_rs485_dma_tx_state
{
    kL02_Rs485DmaTxIdle = 0U,
    kL02_Rs485DmaTxActive,
    kL02_Rs485DmaTxDirectionReleasePending
} l02_rs485_dma_tx_state_t;

typedef enum _l02_rs485_dma_rx_state
{
    kL02_Rs485DmaRxIdle = 0U,
    kL02_Rs485DmaRxActive,
    kL02_Rs485DmaRxFrameReady
} l02_rs485_dma_rx_state_t;

typedef struct _l02_rs485_dma_hardware
{
    USART_Type *usart;
    usart_dma_handle_t *usartDmaHandle;
    dma_handle_t *txDmaHandle;
    dma_handle_t *rxDmaHandle;
} l02_rs485_dma_hardware_t;

typedef struct _l02_rs485_dma_context
{
    l02_rs485_channel_t channel;
    volatile l02_rs485_dma_tx_state_t txState;
    volatile bool rxDmaFullPending;
    l02_rs485_dma_rx_state_t rxState;
    uint32_t rxTimeoutTicks;
    uint32_t rxLastActivityTick;
    uint32_t rxLastCount;
    size_t rxFrameLength;
    size_t rxCapacity;
    bool rxHasData;
    bool initialized;
} l02_rs485_dma_context_t;

static const l02_rs485_dma_hardware_t s_rs485DmaHardware[kL02_Rs485ChannelCount] = {
    {
        UART0_FC0_PERIPHERAL,
        &UART0_FC0_USART_DMA_Handle,
        &UART0_FC0_TX_Handle,
        &UART0_FC0_RX_Handle,
    },
    {
        UART1_FC1_PERIPHERAL,
        &UART1_FC1_USART_DMA_Handle,
        &UART1_FC1_TX_Handle,
        &UART1_FC1_RX_Handle,
    },
};

static l02_rs485_dma_context_t s_rs485DmaContext[kL02_Rs485ChannelCount] = {
    {
        .channel = kL02_Rs485Channel0,
        .txState = kL02_Rs485DmaTxIdle,
        .rxTimeoutTicks = 10U,
    },
    {
        .channel = kL02_Rs485Channel1,
        .txState = kL02_Rs485DmaTxIdle,
        .rxTimeoutTicks = 10U,
    },
};

static volatile uint32_t s_rs485TimerTick100us;

static bool L02_Rs485Dma_IsChannelIndexValid(l02_rs485_channel_t channel)
{
    return ((uint32_t)channel < (uint32_t)kL02_Rs485ChannelCount);
}

static void L02_Rs485Dma_Callback(USART_Type *base,
                                  usart_dma_handle_t *handle,
                                  status_t status,
                                  void *userData)
{
    l02_rs485_dma_context_t *context = (l02_rs485_dma_context_t *)userData;

    (void)base;
    (void)handle;

    if (context != NULL)
    {
        if (status == kStatus_USART_TxIdle)
        {
            /*
             * ISR rule: publish only. Post-TX delay and GPIO access are
             * deferred to L02_Rs485Dma_Process().
             */
            context->txState = kL02_Rs485DmaTxDirectionReleasePending;
        }
        else if (status == kStatus_USART_RxIdle)
        {
            /* DMA filled the complete user buffer. Finalization is deferred. */
            context->rxDmaFullPending = true;
        }
        else
        {
            /* Other USART status values are not generated by this DMA driver. */
        }
    }
}

static status_t L02_Rs485Dma_InitChannel(l02_rs485_channel_t channel)
{
    const l02_rs485_dma_hardware_t *hardware = &s_rs485DmaHardware[(uint32_t)channel];
    l02_rs485_dma_context_t *context = &s_rs485DmaContext[(uint32_t)channel];
    status_t status;

    context->txState = kL02_Rs485DmaTxIdle;
    context->rxState = kL02_Rs485DmaRxIdle;
    context->rxDmaFullPending = false;
    context->rxTimeoutTicks = 10U;
    context->rxLastActivityTick = 0U;
    context->rxLastCount = 0U;
    context->rxFrameLength = 0U;
    context->rxCapacity = 0U;
    context->rxHasData = false;
    context->initialized = false;

    status = USART_TransferCreateHandleDMA(hardware->usart,
                                           hardware->usartDmaHandle,
                                           L02_Rs485Dma_Callback,
                                           context,
                                           hardware->txDmaHandle,
                                           hardware->rxDmaHandle);
    if (status == kStatus_Success)
    {
        context->initialized = true;
    }

    return status;
}

static void L02_Rs485Dma_InitTimer(void)
{
    ctimer_match_config_t tickConfig = COMM_CTIMER4_Match_0_config;

    /*
     * The generated timer clock is 10 kHz. Convert its original 1 ms one-shot
     * match into a continuous 100 us time base without changing Wizard files.
     */
    tickConfig.matchValue = 0U;
    tickConfig.enableCounterReset = true;
    tickConfig.enableCounterStop = false;
    tickConfig.enableInterrupt = true;

    CTIMER_StopTimer(COMM_CTIMER4_PERIPHERAL);
    CTIMER_Reset(COMM_CTIMER4_PERIPHERAL);
    CTIMER_ClearStatusFlags(COMM_CTIMER4_PERIPHERAL, (uint32_t)kCTIMER_Match1Flag);
    CTIMER_SetupMatch(COMM_CTIMER4_PERIPHERAL, COMM_CTIMER4_MATCH_0_CHANNEL, &tickConfig);

    s_rs485TimerTick100us = 0U;
    CTIMER_StartTimer(COMM_CTIMER4_PERIPHERAL);
}

static void L02_Rs485Dma_FinalizeReceive(l02_rs485_dma_context_t *context, size_t length)
{
    context->rxFrameLength = length;
    context->rxState = (length != 0U) ? kL02_Rs485DmaRxFrameReady : kL02_Rs485DmaRxIdle;
    context->rxDmaFullPending = false;
    context->rxHasData = false;
}

static void L02_Rs485Dma_ProcessReceive(l02_rs485_dma_context_t *context, uint32_t now)
{
    const l02_rs485_dma_hardware_t *hardware;
    uint32_t receivedCount;
    status_t countStatus;

    if (context->rxState != kL02_Rs485DmaRxActive)
    {
        return;
    }

    hardware = &s_rs485DmaHardware[(uint32_t)context->channel];

    if (context->rxDmaFullPending)
    {
        L02_Rs485Dma_FinalizeReceive(context, context->rxCapacity);
        return;
    }

    countStatus = USART_TransferGetReceiveCountDMA(hardware->usart,
                                                   hardware->usartDmaHandle,
                                                   &receivedCount);
    if (countStatus == kStatus_Success)
    {
        if (receivedCount != context->rxLastCount)
        {
            context->rxLastCount = receivedCount;
            context->rxLastActivityTick = now;
            context->rxHasData = (receivedCount != 0U);
        }

        if (context->rxHasData &&
            ((uint32_t)(now - context->rxLastActivityTick) >= context->rxTimeoutTicks))
        {
            /*
             * Stop new DMA requests before sampling the final byte count.
             * The timeout denotes a silent bus, so no byte should race this step.
             */
            USART_EnableRxDMA(hardware->usart, false);
            (void)USART_TransferGetReceiveCountDMA(hardware->usart,
                                                   hardware->usartDmaHandle,
                                                   &receivedCount);
            USART_TransferAbortReceiveDMA(hardware->usart, hardware->usartDmaHandle);
            L02_Rs485Dma_FinalizeReceive(context, (size_t)receivedCount);
        }
    }
}

status_t L02_Rs485Dma_Init(void)
{
    status_t status;

#if (PRODUCT_FC0_MODE == PRODUCT_FC0_MODE_RS485)
    status = L02_Rs485Dma_InitChannel(kL02_Rs485Channel0);
    if (status != kStatus_Success)
    {
        return status;
    }
#endif

    status = L02_Rs485Dma_InitChannel(kL02_Rs485Channel1);
    if (status == kStatus_Success)
    {
        L02_Rs485Dma_InitTimer();
    }

    return status;
}

status_t L02_Rs485Dma_SendAsync(l02_rs485_channel_t channel, const uint8_t *data, size_t length)
{
    l02_rs485_dma_context_t *context;
    const l02_rs485_dma_hardware_t *hardware;
    usart_transfer_t transfer;
    status_t status;

    if ((data == NULL) || (length == 0U) || !L02_Rs485Dma_IsChannelIndexValid(channel))
    {
        return kStatus_InvalidArgument;
    }

    context = &s_rs485DmaContext[(uint32_t)channel];
    hardware = &s_rs485DmaHardware[(uint32_t)channel];

    if (!context->initialized)
    {
        return kStatus_InvalidArgument;
    }

    if ((context->txState != kL02_Rs485DmaTxIdle) ||
        (context->rxState != kL02_Rs485DmaRxIdle))
    {
        return kStatus_Busy;
    }

    status = L02_Rs485Direction_BeginTransmit(channel);
    if (status != kStatus_Success)
    {
        return status;
    }

    transfer.txData = (uint8_t *)data;
    transfer.dataSize = length;

    /*
     * Set active before enabling DMA. Otherwise a very short transfer could
     * complete in an interrupt before the state is updated here.
     */
    context->txState = kL02_Rs485DmaTxActive;
    status = USART_TransferSendDMA(hardware->usart, hardware->usartDmaHandle, &transfer);
    if (status != kStatus_Success)
    {
        context->txState = kL02_Rs485DmaTxIdle;
        (void)L02_Rs485Direction_ForceReceive(channel);
    }

    return status;
}

status_t L02_Rs485Dma_IsTransmitBusy(l02_rs485_channel_t channel, bool *isBusy)
{
    l02_rs485_dma_context_t *context;

    if ((isBusy == NULL) || !L02_Rs485Dma_IsChannelIndexValid(channel))
    {
        return kStatus_InvalidArgument;
    }

    context = &s_rs485DmaContext[(uint32_t)channel];
    if (!context->initialized)
    {
        return kStatus_InvalidArgument;
    }

    *isBusy = (context->txState != kL02_Rs485DmaTxIdle);
    return kStatus_Success;
}

status_t L02_Rs485Dma_SetReceiveTimeoutUs(l02_rs485_channel_t channel, uint32_t timeoutUs)
{
    l02_rs485_dma_context_t *context;
    uint64_t ticks;

    if ((timeoutUs == 0U) || !L02_Rs485Dma_IsChannelIndexValid(channel))
    {
        return kStatus_InvalidArgument;
    }

    context = &s_rs485DmaContext[(uint32_t)channel];
    if (!context->initialized)
    {
        return kStatus_InvalidArgument;
    }

    ticks = (((uint64_t)timeoutUs * (uint64_t)COMM_CTIMER4_TICK_FREQ) + 999999ULL) / 1000000ULL;
    if ((ticks == 0ULL) || (ticks > (uint64_t)UINT32_MAX))
    {
        return kStatus_OutOfRange;
    }

    context->rxTimeoutTicks = (uint32_t)ticks;
    return kStatus_Success;
}

status_t L02_Rs485Dma_StartReceive(l02_rs485_channel_t channel, uint8_t *buffer, size_t capacity)
{
    l02_rs485_dma_context_t *context;
    const l02_rs485_dma_hardware_t *hardware;
    usart_transfer_t transfer;
    status_t status;

    if ((buffer == NULL) || (capacity == 0U) || !L02_Rs485Dma_IsChannelIndexValid(channel))
    {
        return kStatus_InvalidArgument;
    }

    context = &s_rs485DmaContext[(uint32_t)channel];
    hardware = &s_rs485DmaHardware[(uint32_t)channel];

    if (!context->initialized)
    {
        return kStatus_InvalidArgument;
    }

    if ((context->txState != kL02_Rs485DmaTxIdle) ||
        (context->rxState != kL02_Rs485DmaRxIdle))
    {
        return kStatus_Busy;
    }

    transfer.data = buffer;
    transfer.dataSize = capacity;

    context->rxState = kL02_Rs485DmaRxActive;
    context->rxDmaFullPending = false;
    context->rxLastActivityTick = s_rs485TimerTick100us;
    context->rxLastCount = 0U;
    context->rxFrameLength = 0U;
    context->rxCapacity = capacity;
    context->rxHasData = false;

    status = USART_TransferReceiveDMA(hardware->usart, hardware->usartDmaHandle, &transfer);
    if (status != kStatus_Success)
    {
        context->rxState = kL02_Rs485DmaRxIdle;
        context->rxCapacity = 0U;
    }

    return status;
}

status_t L02_Rs485Dma_TakeReceivedFrame(l02_rs485_channel_t channel, size_t *length)
{
    l02_rs485_dma_context_t *context;

    if ((length == NULL) || !L02_Rs485Dma_IsChannelIndexValid(channel))
    {
        return kStatus_InvalidArgument;
    }

    context = &s_rs485DmaContext[(uint32_t)channel];
    if (!context->initialized)
    {
        return kStatus_InvalidArgument;
    }

    if (context->rxState != kL02_Rs485DmaRxFrameReady)
    {
        return kStatus_NoData;
    }

    *length = context->rxFrameLength;
    context->rxFrameLength = 0U;
    context->rxCapacity = 0U;
    context->rxState = kL02_Rs485DmaRxIdle;

    return kStatus_Success;
}

status_t L02_Rs485Dma_CancelReceive(l02_rs485_channel_t channel)
{
    l02_rs485_dma_context_t *context;
    const l02_rs485_dma_hardware_t *hardware;

    if (!L02_Rs485Dma_IsChannelIndexValid(channel))
    {
        return kStatus_InvalidArgument;
    }

    context = &s_rs485DmaContext[(uint32_t)channel];
    hardware = &s_rs485DmaHardware[(uint32_t)channel];

    if (!context->initialized)
    {
        return kStatus_InvalidArgument;
    }

    if (context->rxState == kL02_Rs485DmaRxActive)
    {
        USART_EnableRxDMA(hardware->usart, false);
        USART_TransferAbortReceiveDMA(hardware->usart, hardware->usartDmaHandle);
    }

    context->rxState = kL02_Rs485DmaRxIdle;
    context->rxDmaFullPending = false;
    context->rxLastCount = 0U;
    context->rxFrameLength = 0U;
    context->rxCapacity = 0U;
    context->rxHasData = false;

    return kStatus_Success;
}

void L02_Rs485Dma_Process(void)
{
    uint32_t index;
    uint32_t now = s_rs485TimerTick100us;

    for (index = 0U; index < (uint32_t)kL02_Rs485ChannelCount; index++)
    {
        l02_rs485_dma_context_t *context = &s_rs485DmaContext[index];

        if (!context->initialized)
        {
            continue;
        }

        if (context->txState == kL02_Rs485DmaTxDirectionReleasePending)
        {
            /*
             * The SDK callback is raised by the USART TXIDLE IRQ, so one
             * microsecond of timeout is only a defensive register re-check.
             */
            if (L02_Rs485Direction_EndTransmitBlocking(context->channel, 1U) == kStatus_Success)
            {
                context->txState = kL02_Rs485DmaTxIdle;
            }
        }

        L02_Rs485Dma_ProcessReceive(context, now);
    }
}

void L02_Rs485Dma_TimerCallback(uint32_t flags)
{
    if ((flags & (uint32_t)kCTIMER_Match1Flag) != 0U)
    {
        /* ISR rule: publish time only; DMA and frame state stay in main context. */
        s_rs485TimerTick100us++;
    }
}
