#ifndef PRODUCT_TC_K_TABLE_H
#define PRODUCT_TC_K_TABLE_H

#include "PiecewiseLinearTable.h"

#ifdef __cplusplus
extern "C" {
#endif

#define PRODUCT_TC_K_TABLE_COMPLETE (1U)

#define PRODUCT_TC_K_MIN_MILLICELSIUS   (-200000L)
#define PRODUCT_TC_K_MAX_MILLICELSIUS   (1300000L)
#define PRODUCT_TC_K_EXTENDED_MARGIN_MC (20000L)

#define PRODUCT_TC_K_MEASUREMENT_SEGMENT_COUNT (77U)
#define PRODUCT_TC_K_MEASUREMENT_BOUNDARY_COUNT (PRODUCT_TC_K_MEASUREMENT_SEGMENT_COUNT + 1U)
#define PRODUCT_TC_K_INPUT_SHIFT_UV (6200L)
#define PRODUCT_TC_K_MEASUREMENT_COEFFICIENT_SCALE (100UL)

#define PRODUCT_TC_K_CJC_MIN_MILLICELSIUS (-20000L)
#define PRODUCT_TC_K_CJC_MAX_MILLICELSIUS (109000L)
#define PRODUCT_TC_K_CJC_INTERVAL_MC (10000L)
#define PRODUCT_TC_K_CJC_SEGMENT_COUNT (13U)
#define PRODUCT_TC_K_CJC_INPUT_SHIFT_DECICELSIUS (200L)
#define PRODUCT_TC_K_CJC_COEFFICIENT_SCALE (1000UL)

const PiecewiseLinearTable_t *ProductTcKTable_GetMeasurementTable(void);
const PiecewiseLinearTable_t *ProductTcKTable_GetCjcTable(void);
bool ProductTcKTable_IsReady(void);

#ifdef __cplusplus
}
#endif

#endif /* PRODUCT_TC_K_TABLE_H */
