/***********************************************************************************************************************
 * This file was generated by the MCUXpresso Config Tools. Any manual edits made to this file
 * will be overwritten if the respective MCUXpresso Config Tools is used to update this file.
 **********************************************************************************************************************/

#ifndef _CLOCK_CONFIG_H_
#define _CLOCK_CONFIG_H_

#include "fsl_common.h"

/*******************************************************************************
 * Definitions
 ******************************************************************************/
#define BOARD_XTAL32K_CLK_HZ                          32768U  /*!< Board xtal32K frequency in Hz */

/*******************************************************************************
 ************************ BOARD_InitBootClocks function ************************
 ******************************************************************************/

#if defined(__cplusplus)
extern "C" {
#endif /* __cplusplus*/

/*!
 * @brief This function executes default configuration of clocks.
 *
 */
void BOARD_InitBootClocks(void);

#if defined(__cplusplus)
}
#endif /* __cplusplus*/

/*******************************************************************************
 ******************** Configuration BOARD_BootClockPLL150M *********************
 ******************************************************************************/
/*******************************************************************************
 * Definitions for BOARD_BootClockPLL150M configuration
 ******************************************************************************/
#define BOARD_BOOTCLOCKPLL150M_CORE_CLOCK         150000000U  /*!< Core clock frequency: 150000000Hz */


/* Clock outputs (values are in Hz): */
#define BOARD_BOOTCLOCKPLL150M_ASYNCADC_CLOCK         48000000UL
#define BOARD_BOOTCLOCKPLL150M_CAN_CLOCK              15000000UL
#define BOARD_BOOTCLOCKPLL150M_CLKOUT_CLOCK           0UL
#define BOARD_BOOTCLOCKPLL150M_CTIMER0_CLOCK          1000000UL
#define BOARD_BOOTCLOCKPLL150M_CTIMER1_CLOCK          1000000UL
#define BOARD_BOOTCLOCKPLL150M_CTIMER2_CLOCK          1000000UL
#define BOARD_BOOTCLOCKPLL150M_CTIMER3_CLOCK          1000000UL
#define BOARD_BOOTCLOCKPLL150M_CTIMER4_CLOCK          1000000UL
#define BOARD_BOOTCLOCKPLL150M_FRO_12MHZ_CLOCK        12000000UL
#define BOARD_BOOTCLOCKPLL150M_FRO_1MHZ_CLOCK         1000000UL
#define BOARD_BOOTCLOCKPLL150M_FXCOM0_CLOCK           12000000UL
#define BOARD_BOOTCLOCKPLL150M_FXCOM1_CLOCK           12000000UL
#define BOARD_BOOTCLOCKPLL150M_FXCOM2_CLOCK           48000000UL
#define BOARD_BOOTCLOCKPLL150M_FXCOM3_CLOCK           48000000UL
#define BOARD_BOOTCLOCKPLL150M_FXCOM4_CLOCK           48000000UL
#define BOARD_BOOTCLOCKPLL150M_FXCOM5_CLOCK           48000000UL
#define BOARD_BOOTCLOCKPLL150M_FXCOM6_CLOCK           48000000UL
#define BOARD_BOOTCLOCKPLL150M_FXCOM7_CLOCK           48000000UL
#define BOARD_BOOTCLOCKPLL150M_HSLSPI_CLOCK           48000000UL
#define BOARD_BOOTCLOCKPLL150M_HSUSB1_32K_CLOCK       0UL
#define BOARD_BOOTCLOCKPLL150M_MCLK_CLOCK             0UL
#define BOARD_BOOTCLOCKPLL150M_OSC32KHZ_CLOCK         0UL
#define BOARD_BOOTCLOCKPLL150M_OSTIMER_CLOCK          0UL
#define BOARD_BOOTCLOCKPLL150M_PLUCLKIN_CLOCK         0UL
#define BOARD_BOOTCLOCKPLL150M_PLU_GLITCH_12MHZ_CLOCK 0UL
#define BOARD_BOOTCLOCKPLL150M_PLU_GLITCH_1MHZ_CLOCK  0UL
#define BOARD_BOOTCLOCKPLL150M_RTC1HZ_CLOCK           0UL
#define BOARD_BOOTCLOCKPLL150M_RTC1KHZ_CLOCK          0UL
#define BOARD_BOOTCLOCKPLL150M_SCT_CLOCK              0UL
#define BOARD_BOOTCLOCKPLL150M_SYSTICK0_CLOCK         150000000UL
#define BOARD_BOOTCLOCKPLL150M_SYSTEM_CLOCK           150000000UL
#define BOARD_BOOTCLOCKPLL150M_TRACE_CLOCK            0UL
#define BOARD_BOOTCLOCKPLL150M_USB0_CLOCK             48000000UL
#define BOARD_BOOTCLOCKPLL150M_USB1_PHY_CLOCK         0UL
#define BOARD_BOOTCLOCKPLL150M_UTICK_CLOCK            0UL
#define BOARD_BOOTCLOCKPLL150M_WDT_CLOCK              1000000UL

/*******************************************************************************
 * API for BOARD_BootClockPLL150M configuration
 ******************************************************************************/
#if defined(__cplusplus)
extern "C" {
#endif /* __cplusplus*/

/*!
 * @brief This function executes configuration of clocks.
 *
 */
void BOARD_BootClockPLL150M(void);

#if defined(__cplusplus)
}
#endif /* __cplusplus*/

#endif /* _CLOCK_CONFIG_H_ */

