/***********************************************************************************************************************
 * This file was generated by the MCUXpresso Config Tools. Any manual edits made to this file
 * will be overwritten if the respective MCUXpresso Config Tools is used to update this file.
 **********************************************************************************************************************/

#ifndef _PERIPHERALS_H_
#define _PERIPHERALS_H_

/***********************************************************************************************************************
 * Included files
 **********************************************************************************************************************/
#include "fsl_dma.h"
#include "fsl_common.h"
#include "fsl_wwdt.h"
#include "fsl_ctimer.h"
#include "fsl_clock.h"
#include "fsl_reset.h"
#include "fsl_usart.h"
#include "fsl_usart_dma.h"
#include "fsl_spi.h"
#include "fsl_lpadc.h"
#include "fsl_power.h"
#include "fsl_crc.h"
#include "fsl_pint.h"
#include "fsl_mrt.h"

#if defined(__cplusplus)
extern "C" {
#endif /* __cplusplus */

/***********************************************************************************************************************
 * Definitions
 **********************************************************************************************************************/
/* Definitions for BOARD_InitPeripherals functional group */
/* Used DMA device. */
#define DMA0_DMA_BASEADDR DMA0
/* Used DMA device. */
#define DMA1_DMA_BASEADDR DMA1
/* NVIC interrupt vector ID (number). */
#define UART0_FC0_IRQN FLEXCOMM0_IRQn
/* NVIC interrupt handler identifier. */
#define UART0_FC0_IRQHANDLER FLEXCOMM0_IRQHandler
/* NVIC interrupt vector ID (number). */
#define UART1_FC1_IRQN FLEXCOMM1_IRQn
/* NVIC interrupt handler identifier. */
#define UART1_FC1_IRQHANDLER FLEXCOMM1_IRQHandler
/* BOARD_InitPeripherals defines for WWDT */
/* Definition of peripheral ID */
#define WWDT_PERIPHERAL ((WWDT_Type *) WWDT_BASE)
/* Definition of the Watchdog Timer Window value */
#define WWDT_WINDOW 16777215UL
/* Definition of the Watchdog Timer Constant value */
#define WWDT_TIMEOUT 500000UL
/* Definition of the Watchdog Timer Warning Interrupt value */
#define WWDT_WARNING 0UL
/* WWDT interrupt vector ID (number). */
#define WWDT_IRQN WDT_BOD_IRQn
/* WWDT interrupt handler identifier. */
#define WWDT_IRQHANDLER WDT_BOD_IRQHandler
/* Definition of peripheral ID */
#define OUT4_CTIMER2_PERIPHERAL CTIMER2
/* Timer tick frequency in Hz (input frequency of the timer) */
#define OUT4_CTIMER2_TICK_FREQ 10000UL
/* Timer tick period in ns (input period of the timer) */
#define OUT4_CTIMER2_TICK_PERIOD 100000UL
/* Definition of PWM period channel. */
#define OUT4_CTIMER2_PWM_PERIOD_CH kCTIMER_Match_0
/* Definition of PWM period */
#define OUT4_CTIMER2_PWM_PERIOD 39999
/* OUT4_CTIMER2 interrupt vector ID (number). */
#define OUT4_CTIMER2_TIMER_IRQN CTIMER2_IRQn
/* Definition of peripheral ID */
#define OUT1_CTIMER0_PERIPHERAL CTIMER0
/* Timer tick frequency in Hz (input frequency of the timer) */
#define OUT1_CTIMER0_TICK_FREQ 10000UL
/* Timer tick period in ns (input period of the timer) */
#define OUT1_CTIMER0_TICK_PERIOD 100000UL
/* Definition of PWM period channel. */
#define OUT1_CTIMER0_PWM_PERIOD_CH kCTIMER_Match_3
/* Definition of PWM period */
#define OUT1_CTIMER0_PWM_PERIOD 39999
/* OUT1_CTIMER0 interrupt vector ID (number). */
#define OUT1_CTIMER0_TIMER_IRQN CTIMER0_IRQn
/* Definition of peripheral ID */
#define OUT2_CTIMER1_PERIPHERAL CTIMER1
/* Timer tick frequency in Hz (input frequency of the timer) */
#define OUT2_CTIMER1_TICK_FREQ 10000UL
/* Timer tick period in ns (input period of the timer) */
#define OUT2_CTIMER1_TICK_PERIOD 100000UL
/* Definition of PWM period channel. */
#define OUT2_CTIMER1_PWM_PERIOD_CH kCTIMER_Match_3
/* Definition of PWM period */
#define OUT2_CTIMER1_PWM_PERIOD 39999
/* OUT2_CTIMER1 interrupt vector ID (number). */
#define OUT2_CTIMER1_TIMER_IRQN CTIMER1_IRQn
/* Definition of peripheral ID */
#define OUT3_CTIMER3_PERIPHERAL CTIMER3
/* Timer tick frequency in Hz (input frequency of the timer) */
#define OUT3_CTIMER3_TICK_FREQ 10000UL
/* Timer tick period in ns (input period of the timer) */
#define OUT3_CTIMER3_TICK_PERIOD 100000UL
/* Definition of PWM period channel. */
#define OUT3_CTIMER3_PWM_PERIOD_CH kCTIMER_Match_3
/* Definition of PWM period */
#define OUT3_CTIMER3_PWM_PERIOD 39999
/* OUT3_CTIMER3 interrupt vector ID (number). */
#define OUT3_CTIMER3_TIMER_IRQN CTIMER3_IRQn
/* Definition of peripheral ID */
#define UART0_FC0_PERIPHERAL ((USART_Type *)FLEXCOMM0)
/* Definition of the clock source frequency */
#define UART0_FC0_CLOCK_SOURCE 12000000UL
/* Selected DMA channel number. */
#define UART0_FC0_RX_DMA_CHANNEL 4
/* Used DMA device. */
#define UART0_FC0_RX_DMA_BASEADDR DMA0
/* Selected DMA channel number. */
#define UART0_FC0_TX_DMA_CHANNEL 5
/* Used DMA device. */
#define UART0_FC0_TX_DMA_BASEADDR DMA0
/* Definition of peripheral ID */
#define UART1_FC1_PERIPHERAL ((USART_Type *)FLEXCOMM1)
/* Definition of the clock source frequency */
#define UART1_FC1_CLOCK_SOURCE 12000000UL
/* Selected DMA channel number. */
#define UART1_FC1_RX_DMA_CHANNEL 6
/* Used DMA device. */
#define UART1_FC1_RX_DMA_BASEADDR DMA0
/* Selected DMA channel number. */
#define UART1_FC1_TX_DMA_CHANNEL 7
/* Used DMA device. */
#define UART1_FC1_TX_DMA_BASEADDR DMA0
/* BOARD_InitPeripherals defines for FLEXCOMM3 */
/* Definition of peripheral ID */
#define ADC_FC3_PERIPHERAL ((SPI_Type *)FLEXCOMM3)
/* Definition of the clock source frequency */
#define ADC_FC3_CLOCK_SOURCE 48000000UL
/* ADC_FC3 interrupt vector ID (number). */
#define ADC_FC3_FLEXCOMM_IRQN FLEXCOMM3_IRQn
/* BOARD_InitPeripherals defines for FLEXCOMM8 */
/* Definition of peripheral ID */
#define DIPSW_SPI_PERIPHERAL ((SPI_Type *)FLEXCOMM8)
/* Definition of the clock source frequency */
#define DIPSW_SPI_CLOCK_SOURCE 48000000UL
/* DIPSW_SPI interrupt vector ID (number). */
#define DIPSW_SPI_FLEXCOMM_IRQN FLEXCOMM8_IRQn
/* Alias for ADC0 peripheral */
#define CJC_ADC0_PERIPHERAL ADC0
/* CJC_ADC0 interrupt vector ID (number). */
#define CJC_ADC0_IRQN ADC0_IRQn
/* CJC_ADC0 interrupt handler identifier. */
#define CJC_ADC0_IRQHANDLER ADC0_IRQHandler
/* Command 1 - CJC0_Cmd */
#define CJC_ADC0_CJC0_CMD 1U
/* Command 2 - CJC1_Cmd */
#define CJC_ADC0_CJC1_CMD 2U
/* Command 3 - ChipTemp_Cmd */
#define CJC_ADC0_CHIPTEMP_CMD 3U
/* Trigger 0 - CJC0_Trig */
#define CJC_ADC0_CJC0_TRIG 0U
/* Trigger 1 - CJC1_Trig */
#define CJC_ADC0_CJC1_TRIG 1U
/* Trigger 2 - ChipTemp_Trig */
#define CJC_ADC0_CHIPTEMP_TRIG 2U
/* BOARD_InitPeripherals defines for FLEXCOMM5 */
/* Definition of peripheral ID */
#define DAC_FC5_PERIPHERAL ((SPI_Type *)FLEXCOMM5)
/* Definition of the clock source frequency */
#define DAC_FC5_CLOCK_SOURCE 48000000UL
/* DAC_FC5 interrupt vector ID (number). */
#define DAC_FC5_FLEXCOMM_IRQN FLEXCOMM5_IRQn
/* BOARD_InitPeripherals defines for FLEXCOMM7 */
/* Definition of peripheral ID */
#define MEM_FC7_PERIPHERAL ((SPI_Type *)FLEXCOMM7)
/* Definition of the clock source frequency */
#define MEM_FC7_CLOCK_SOURCE 48000000UL
/* MEM_FC7 interrupt vector ID (number). */
#define MEM_FC7_FLEXCOMM_IRQN FLEXCOMM7_IRQn
/* Definition of peripheral ID */
#define COMM_CTIMER4_PERIPHERAL CTIMER4
/* Timer tick frequency in Hz (input frequency of the timer) */
#define COMM_CTIMER4_TICK_FREQ 10000UL
/* Timer tick period in ns (input period of the timer) */
#define COMM_CTIMER4_TICK_PERIOD 100000UL
/* Definition of PWM period channel. */
#define COMM_CTIMER4_PWM_PERIOD_CH kCTIMER_Match_0
/* Definition of channel 1 ID */
#define COMM_CTIMER4_MATCH_0_CHANNEL kCTIMER_Match_1
/* COMM_CTIMER4 interrupt vector ID (number). */
#define COMM_CTIMER4_TIMER_IRQN CTIMER4_IRQn
/* Definition of peripheral ID */
#define CRC_ENGINE_PERIPHERAL CRC_ENGINE
/* BOARD_InitPeripherals defines for PINT */
/* Definition of peripheral ID */
#define PINT_PERIPHERAL ((PINT_Type *) PINT_BASE)
/* PINT interrupt vector ID (number). */
#define PINT_PINT_0_IRQN PIN_INT0_IRQn
/* Definition of PINT interrupt ID for interrupt 0  */
#define PINT_INT_0 kPINT_PinInt0
/* BOARD_InitPeripherals defines for PINT */
/* Definition of peripheral ID */
#define PINT_CLK_PERIPHERAL ((PINT_Type *) PINT_BASE)
/* PINT_CLK interrupt vector ID (number). */
#define PINT_CLK_PINT_1_IRQN PIN_INT1_IRQn
/* Definition of PINT interrupt ID for interrupt 1  */
#define PINT_CLK_INT_1 kPINT_PinInt1
/* Definition of peripheral ID */
#define MRT0_PERIPHERAL MRT0

/***********************************************************************************************************************
 * Global variables
 **********************************************************************************************************************/
extern const wwdt_config_t WWDT_config;
extern const ctimer_config_t OUT4_CTIMER2_config;
extern const ctimer_config_t OUT1_CTIMER0_config;
extern const ctimer_config_t OUT2_CTIMER1_config;
extern const ctimer_config_t OUT3_CTIMER3_config;
extern const usart_config_t UART0_FC0_config;
extern dma_handle_t UART0_FC0_RX_Handle;
extern dma_handle_t UART0_FC0_TX_Handle;
extern usart_dma_handle_t UART0_FC0_USART_DMA_Handle;
extern const usart_config_t UART1_FC1_config;
extern dma_handle_t UART1_FC1_RX_Handle;
extern dma_handle_t UART1_FC1_TX_Handle;
extern usart_dma_handle_t UART1_FC1_USART_DMA_Handle;
extern const spi_master_config_t ADC_FC3_config;
extern spi_master_handle_t ADC_FC3_handle;
extern const spi_master_config_t DIPSW_SPI_config;
extern spi_master_handle_t DIPSW_SPI_handle;
extern const lpadc_config_t CJC_ADC0_config;
extern lpadc_conv_command_config_t CJC_ADC0_commandsConfig[3];
extern lpadc_conv_trigger_config_t CJC_ADC0_triggersConfig[3];
extern const spi_master_config_t DAC_FC5_config;
extern spi_master_handle_t DAC_FC5_handle;
extern const spi_master_config_t MEM_FC7_config;
extern spi_master_handle_t MEM_FC7_handle;
extern const ctimer_config_t COMM_CTIMER4_config;
extern const ctimer_match_config_t COMM_CTIMER4_Match_0_config;
extern const crc_config_t CRC_ENGINE_config;
extern const mrt_config_t MRT0_config;

/***********************************************************************************************************************
 * Callback functions
 **********************************************************************************************************************/
  /* Single callback function declaration */
extern void ctimer2_match3_callback(uint32_t flags);
extern ctimer_callback_t OUT4_CTIMER2_callback[];
  /* Single callback function declaration */
extern void ctimer0_match0_callback(uint32_t flags);
extern ctimer_callback_t OUT1_CTIMER0_callback[];
  /* Single callback function declaration */
extern void ctimer1_match0_callback(uint32_t flags);
extern ctimer_callback_t OUT2_CTIMER1_callback[];
  /* Single callback function declaration */
extern void ctimer3_match1_callback(uint32_t flags);
extern ctimer_callback_t OUT3_CTIMER3_callback[];
  /* Single callback function declaration */
extern void COMM_TMOut_callback(uint32_t flags);
extern ctimer_callback_t COMM_CTIMER4_callback[];
/* INT_0 callback function for the PINT component */
extern void drv_level_detect_callback(pint_pin_int_t pintr, uint32_t pmatch_status);
/* INT_1 callback function for the PINT_CLK component */
extern void drv_internalbus_clk_callback(pint_pin_int_t pintr, uint32_t pmatch_status);

/***********************************************************************************************************************
 * Initialization functions
 **********************************************************************************************************************/

void BOARD_InitPeripherals(void);

/***********************************************************************************************************************
 * BOARD_InitBootPeripherals function
 **********************************************************************************************************************/
void BOARD_InitBootPeripherals(void);

#if defined(__cplusplus)
}
#endif

#endif /* _PERIPHERALS_H_ */
