/***********************************************************************************************************************
 * This file was generated by the MCUXpresso Config Tools. Any manual edits made to this file
 * will be overwritten if the respective MCUXpresso Config Tools is used to update this file.
 **********************************************************************************************************************/

/* clang-format off */
/* TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
!!GlobalInfo
product: Peripherals v12.0
processor: LPC55S16
package_id: LPC55S16JBD100
mcu_data: ksdk2_0
processor_version: 13.0.1
board: LPCXpresso55S16
functionalGroups:
- name: BOARD_InitPeripherals
  UUID: e48301ba-6eae-42f0-b2e4-0109e547ef26
  called_from_default_init: true
  selectedCore: cm33_core0
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS **********/

/* TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
component:
- type: 'system'
- type_id: 'system_54b53072540eeeb8f8e9343e71f28176'
- global_system_definitions:
  - user_definitions: ''
  - user_includes: ''
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS **********/

/* TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
component:
- type: 'uart_cmsis_common'
- type_id: 'uart_cmsis_common_9cb8e302497aa696fdbb5a4fd622c2a8'
- global_USART_CMSIS_common:
  - quick_selection: 'default'
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS **********/

/* TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
component:
- type: 'gpio_adapter_common'
- type_id: 'gpio_adapter_common_57579b9ac814fe26bf95df0a384c36b6'
- global_gpio_adapter_common:
  - quick_selection: 'default'
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS **********/
/* clang-format on */

/***********************************************************************************************************************
 * Included files
 **********************************************************************************************************************/
#include "peripherals.h"

/***********************************************************************************************************************
 * BOARD_InitPeripherals functional group
 **********************************************************************************************************************/
/***********************************************************************************************************************
 * DMA0 initialization code
 **********************************************************************************************************************/
/* clang-format off */
/* TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
instance:
- name: 'DMA0'
- type: 'lpc_dma'
- mode: 'basic'
- custom_name_enabled: 'false'
- type_id: 'lpc_dma_1e560b38547e8785cc7d22228be0a18c'
- functional_group: 'BOARD_InitPeripherals'
- peripheral: 'DMA0'
- config_sets:
  - fsl_dma:
    - dma_table:
      - 0: []
      - 1: []
      - 2: []
      - 3: []
    - dma_channels: []
    - init_interrupt: 'false'
    - dma_interrupt:
      - IRQn: 'DMA0_IRQn'
      - enable_interrrupt: 'enabled'
      - enable_priority: 'false'
      - priority: '0'
      - enable_custom_name: 'false'
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS **********/
/* clang-format on */

/* Empty initialization function (commented out)
static void DMA0_init(void) {
} */

/***********************************************************************************************************************
 * DMA1 initialization code
 **********************************************************************************************************************/
/* clang-format off */
/* TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
instance:
- name: 'DMA1'
- type: 'lpc_dma'
- mode: 'basic'
- custom_name_enabled: 'false'
- type_id: 'lpc_dma_1e560b38547e8785cc7d22228be0a18c'
- functional_group: 'BOARD_InitPeripherals'
- peripheral: 'DMA1'
- config_sets:
  - fsl_dma:
    - dma_table: []
    - dma_channels: []
    - init_interrupt: 'false'
    - dma_interrupt:
      - IRQn: 'DMA1_IRQn'
      - enable_interrrupt: 'enabled'
      - enable_priority: 'false'
      - priority: '0'
      - enable_custom_name: 'false'
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS **********/
/* clang-format on */

/* Empty initialization function (commented out)
static void DMA1_init(void) {
} */

/***********************************************************************************************************************
 * NVIC initialization code
 **********************************************************************************************************************/
/* clang-format off */
/* TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
instance:
- name: 'NVIC'
- type: 'nvic'
- mode: 'general'
- custom_name_enabled: 'false'
- type_id: 'nvic_57b5eef3774cc60acaede6f5b8bddc67'
- functional_group: 'BOARD_InitPeripherals'
- peripheral: 'NVIC'
- config_sets:
  - nvic:
    - interrupt_table:
      - 0: []
      - 1: []
      - 2: []
      - 3: []
      - 4: []
      - 5: []
      - 6: []
      - 7: []
      - 8: []
      - 9: []
      - 10: []
      - 11: []
      - 12: []
      - 13: []
      - 14: []
    - interrupts:
      - 0:
        - channelId: 'UART0_FC0'
        - interrupt_t:
          - IRQn: 'FLEXCOMM0_IRQn'
          - enable_interrrupt: 'enabled'
          - enable_priority: 'false'
          - priority: '0'
          - enable_custom_name: 'false'
      - 1:
        - channelId: 'UART1_FC1'
        - interrupt_t:
          - IRQn: 'FLEXCOMM1_IRQn'
          - enable_interrrupt: 'enabled'
          - enable_priority: 'false'
          - priority: '0'
          - enable_custom_name: 'false'
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS **********/
/* clang-format on */

/* Empty initialization function (commented out)
static void NVIC_init(void) {
} */

/***********************************************************************************************************************
 * WWDT initialization code
 **********************************************************************************************************************/
/* clang-format off */
/* TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
instance:
- name: 'WWDT'
- type: 'wwdt'
- mode: 'reset_mode'
- custom_name_enabled: 'false'
- type_id: 'wwdt_4afd1b7f7bc88fc51c044e9c38c1808c'
- functional_group: 'BOARD_InitPeripherals'
- peripheral: 'WWDT'
- config_sets:
  - general:
    - wwdt_config:
      - clockSource: 'FunctionClock'
      - clockSourceFreq: 'BOARD_BootClockPLL150M'
      - enableWwdt: 'true'
      - enableWatchdogProtect: 'false'
      - timeoutValue_input: '500000'
      - windowEnable: 'false'
      - warningValue_input: '0'
    - interrupt:
      - IRQn: 'WDT_BOD_IRQn'
      - enable_interrrupt: 'enabled'
      - enable_priority: 'false'
      - priority: '0'
      - enable_custom_name: 'false'
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS **********/
/* clang-format on */
const wwdt_config_t WWDT_config = {
  .enableWwdt = true,
  .enableWatchdogReset = true,
  .enableWatchdogProtect = false,
  .windowValue = WWDT_WINDOW,
  .timeoutValue = WWDT_TIMEOUT,
  .warningValue = WWDT_WARNING,
  .clockFreq_Hz = 250000
};

static void WWDT_init(void) {
  /* WWDT initiation  */
  WWDT_Init(WWDT_PERIPHERAL, &WWDT_config);
  /* Enable interrupt WDT_BOD_IRQn request in the NVIC. */
  EnableIRQ(WWDT_IRQN);
}

/***********************************************************************************************************************
 * OUT4_CTIMER2 initialization code
 **********************************************************************************************************************/
/* clang-format off */
/* TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
instance:
- name: 'OUT4_CTIMER2'
- type: 'ctimer'
- mode: 'PWM'
- custom_name_enabled: 'true'
- type_id: 'ctimer_44573e4bbd77c18d33bceb2e7900a074'
- functional_group: 'BOARD_InitPeripherals'
- peripheral: 'CTIMER2'
- config_sets:
  - fsl_ctimer:
    - ctimerConfig:
      - mode: 'kCTIMER_TimerMode'
      - clockSource: 'FunctionClock'
      - clockSourceFreq: 'BOARD_BootClockPLL150M'
      - timerPrescaler: '100'
    - EnableTimerInInit: 'true'
    - pwmConfig:
      - pwmPeriodChannel: 'kCTIMER_Match_0'
      - pwmPeriodValueStr: '4s'
      - enableInterrupt: 'true'
      - pwmChannels: []
    - interruptCallbackConfig:
      - interrupt:
        - IRQn: 'CTIMER2_IRQn'
        - enable_priority: 'false'
        - priority: '0'
      - callback: 'kCTIMER_SingleCallback'
      - singleCallback: 'ctimer2_match3_callback'
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS **********/
/* clang-format on */
const ctimer_config_t OUT4_CTIMER2_config = {
  .mode = kCTIMER_TimerMode,
  .input = kCTIMER_Capture_0,
  .prescale = 99
};
/* Single callback functions definition */
ctimer_callback_t OUT4_CTIMER2_callback[] = {ctimer2_match3_callback};

static void OUT4_CTIMER2_init(void) {
  /* CTIMER2 peripheral initialization */
  CTIMER_Init(OUT4_CTIMER2_PERIPHERAL, &OUT4_CTIMER2_config);
  /* Enable interrupt of PWM channel 3 that determinates the PWM period */
  CTIMER_EnableInterrupts(OUT4_CTIMER2_PERIPHERAL, kCTIMER_Match3InterruptEnable);
  CTIMER_RegisterCallBack(OUT4_CTIMER2_PERIPHERAL, OUT4_CTIMER2_callback, kCTIMER_SingleCallback);
  /* Enable interrupt CTIMER2_IRQn request in the NVIC. */
  EnableIRQ(OUT4_CTIMER2_TIMER_IRQN);
  /* Start the timer */
  CTIMER_StartTimer(OUT4_CTIMER2_PERIPHERAL);
}

/***********************************************************************************************************************
 * OUT1_CTIMER0 initialization code
 **********************************************************************************************************************/
/* clang-format off */
/* TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
instance:
- name: 'OUT1_CTIMER0'
- type: 'ctimer'
- mode: 'PWM'
- custom_name_enabled: 'true'
- type_id: 'ctimer_44573e4bbd77c18d33bceb2e7900a074'
- functional_group: 'BOARD_InitPeripherals'
- peripheral: 'CTIMER0'
- config_sets:
  - fsl_ctimer:
    - ctimerConfig:
      - mode: 'kCTIMER_TimerMode'
      - clockSource: 'FunctionClock'
      - clockSourceFreq: 'BOARD_BootClockPLL150M'
      - timerPrescaler: '100'
    - EnableTimerInInit: 'true'
    - pwmConfig:
      - pwmPeriodChannel: 'kCTIMER_Match_3'
      - pwmPeriodValueStr: '4s'
      - enableInterrupt: 'true'
      - pwmChannels: []
    - interruptCallbackConfig:
      - interrupt:
        - IRQn: 'CTIMER0_IRQn'
        - enable_priority: 'false'
        - priority: '0'
      - callback: 'kCTIMER_SingleCallback'
      - singleCallback: 'ctimer0_match0_callback'
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS **********/
/* clang-format on */
const ctimer_config_t OUT1_CTIMER0_config = {
  .mode = kCTIMER_TimerMode,
  .input = kCTIMER_Capture_0,
  .prescale = 99
};
/* Single callback functions definition */
ctimer_callback_t OUT1_CTIMER0_callback[] = {ctimer0_match0_callback};

static void OUT1_CTIMER0_init(void) {
  /* CTIMER0 peripheral initialization */
  CTIMER_Init(OUT1_CTIMER0_PERIPHERAL, &OUT1_CTIMER0_config);
  /* Enable interrupt of PWM channel 3 that determinates the PWM period */
  CTIMER_EnableInterrupts(OUT1_CTIMER0_PERIPHERAL, kCTIMER_Match3InterruptEnable);
  CTIMER_RegisterCallBack(OUT1_CTIMER0_PERIPHERAL, OUT1_CTIMER0_callback, kCTIMER_SingleCallback);
  /* Enable interrupt CTIMER0_IRQn request in the NVIC. */
  EnableIRQ(OUT1_CTIMER0_TIMER_IRQN);
  /* Start the timer */
  CTIMER_StartTimer(OUT1_CTIMER0_PERIPHERAL);
}

/***********************************************************************************************************************
 * OUT2_CTIMER1 initialization code
 **********************************************************************************************************************/
/* clang-format off */
/* TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
instance:
- name: 'OUT2_CTIMER1'
- type: 'ctimer'
- mode: 'PWM'
- custom_name_enabled: 'true'
- type_id: 'ctimer_44573e4bbd77c18d33bceb2e7900a074'
- functional_group: 'BOARD_InitPeripherals'
- peripheral: 'CTIMER1'
- config_sets:
  - fsl_ctimer:
    - ctimerConfig:
      - mode: 'kCTIMER_TimerMode'
      - clockSource: 'FunctionClock'
      - clockSourceFreq: 'BOARD_BootClockPLL150M'
      - timerPrescaler: '100'
    - EnableTimerInInit: 'true'
    - pwmConfig:
      - pwmPeriodChannel: 'kCTIMER_Match_3'
      - pwmPeriodValueStr: '4s'
      - enableInterrupt: 'true'
      - pwmChannels: []
    - interruptCallbackConfig:
      - interrupt:
        - IRQn: 'CTIMER1_IRQn'
        - enable_priority: 'false'
        - priority: '0'
      - callback: 'kCTIMER_SingleCallback'
      - singleCallback: 'ctimer1_match0_callback'
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS **********/
/* clang-format on */
const ctimer_config_t OUT2_CTIMER1_config = {
  .mode = kCTIMER_TimerMode,
  .input = kCTIMER_Capture_0,
  .prescale = 99
};
/* Single callback functions definition */
ctimer_callback_t OUT2_CTIMER1_callback[] = {ctimer1_match0_callback};

static void OUT2_CTIMER1_init(void) {
  /* CTIMER1 peripheral initialization */
  CTIMER_Init(OUT2_CTIMER1_PERIPHERAL, &OUT2_CTIMER1_config);
  /* Enable interrupt of PWM channel 3 that determinates the PWM period */
  CTIMER_EnableInterrupts(OUT2_CTIMER1_PERIPHERAL, kCTIMER_Match3InterruptEnable);
  CTIMER_RegisterCallBack(OUT2_CTIMER1_PERIPHERAL, OUT2_CTIMER1_callback, kCTIMER_SingleCallback);
  /* Enable interrupt CTIMER1_IRQn request in the NVIC. */
  EnableIRQ(OUT2_CTIMER1_TIMER_IRQN);
  /* Start the timer */
  CTIMER_StartTimer(OUT2_CTIMER1_PERIPHERAL);
}

/***********************************************************************************************************************
 * OUT3_CTIMER3 initialization code
 **********************************************************************************************************************/
/* clang-format off */
/* TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
instance:
- name: 'OUT3_CTIMER3'
- type: 'ctimer'
- mode: 'PWM'
- custom_name_enabled: 'true'
- type_id: 'ctimer_44573e4bbd77c18d33bceb2e7900a074'
- functional_group: 'BOARD_InitPeripherals'
- peripheral: 'CTIMER3'
- config_sets:
  - fsl_ctimer:
    - ctimerConfig:
      - mode: 'kCTIMER_TimerMode'
      - clockSource: 'FunctionClock'
      - clockSourceFreq: 'BOARD_BootClockPLL150M'
      - timerPrescaler: '100'
    - EnableTimerInInit: 'true'
    - pwmConfig:
      - pwmPeriodChannel: 'kCTIMER_Match_3'
      - pwmPeriodValueStr: '4s'
      - enableInterrupt: 'true'
      - pwmChannels: []
    - interruptCallbackConfig:
      - interrupt:
        - IRQn: 'CTIMER3_IRQn'
        - enable_priority: 'false'
        - priority: '0'
      - callback: 'kCTIMER_SingleCallback'
      - singleCallback: 'ctimer3_match1_callback'
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS **********/
/* clang-format on */
const ctimer_config_t OUT3_CTIMER3_config = {
  .mode = kCTIMER_TimerMode,
  .input = kCTIMER_Capture_0,
  .prescale = 99
};
/* Single callback functions definition */
ctimer_callback_t OUT3_CTIMER3_callback[] = {ctimer3_match1_callback};

static void OUT3_CTIMER3_init(void) {
  /* CTIMER3 peripheral initialization */
  CTIMER_Init(OUT3_CTIMER3_PERIPHERAL, &OUT3_CTIMER3_config);
  /* Enable interrupt of PWM channel 3 that determinates the PWM period */
  CTIMER_EnableInterrupts(OUT3_CTIMER3_PERIPHERAL, kCTIMER_Match3InterruptEnable);
  CTIMER_RegisterCallBack(OUT3_CTIMER3_PERIPHERAL, OUT3_CTIMER3_callback, kCTIMER_SingleCallback);
  /* Enable interrupt CTIMER3_IRQn request in the NVIC. */
  EnableIRQ(OUT3_CTIMER3_TIMER_IRQN);
  /* Start the timer */
  CTIMER_StartTimer(OUT3_CTIMER3_PERIPHERAL);
}

/***********************************************************************************************************************
 * UART0_FC0 initialization code
 **********************************************************************************************************************/
/* clang-format off */
/* TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
instance:
- name: 'UART0_FC0'
- type: 'flexcomm_usart'
- mode: 'dma'
- custom_name_enabled: 'true'
- type_id: 'flexcomm_usart_ed63debb5f147199906723fc49ad2e72'
- functional_group: 'BOARD_InitPeripherals'
- peripheral: 'FLEXCOMM0'
- config_sets:
  - dmaCfg:
    - dma_channels:
      - enable_rx_dma_channel: 'true'
      - dma_rx_channel:
        - DMA_source: 'kDma0RequestFlexcomm0Rx'
        - init_channel_priority: 'false'
        - dma_priority: 'kDMA_ChannelPriority0'
        - enable_custom_name: 'false'
      - enable_tx_dma_channel: 'true'
      - dma_tx_channel:
        - DMA_source: 'kDma0RequestFlexcomm0Tx'
        - init_channel_priority: 'false'
        - dma_priority: 'kDMA_ChannelPriority0'
        - enable_custom_name: 'false'
    - usart_dma_handle:
      - enable_custom_name: 'false'
      - init_callback: 'false'
      - callback_fcn: ''
      - user_data: ''
    - quick_selection: 'QuickSelection1'
  - usartConfig_t:
    - usartConfig:
      - clockSource: 'FXCOMFunctionClock'
      - clockSourceFreq: 'BOARD_BootClockPLL150M'
      - baudRate_Bps: '115200'
      - syncMode: 'kUSART_SyncModeDisabled'
      - parityMode: 'kUSART_ParityDisabled'
      - stopBitCount: 'kUSART_OneStopBit'
      - bitCountPerChar: 'kUSART_8BitsPerChar'
      - loopback: 'false'
      - txWatermark: 'kUSART_TxFifo0'
      - rxWatermark: 'kUSART_RxFifo1'
      - enableMatchAddress: 'false'
      - matchAddressConfig:
        - matchAddress: '0'
        - addressMode: 'automatic'
      - enableRx: 'true'
      - enableTx: 'true'
      - enableHardwareFlowControl: 'false'
      - enableRTS: 'false'
      - clockPolarity: 'kUSART_RxSampleOnFallingEdge'
      - enableContinuousSCLK: 'false'
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS **********/
/* clang-format on */
const usart_config_t UART0_FC0_config = {
  .baudRate_Bps = 115200UL,
  .syncMode = kUSART_SyncModeDisabled,
  .parityMode = kUSART_ParityDisabled,
  .stopBitCount = kUSART_OneStopBit,
  .bitCountPerChar = kUSART_8BitsPerChar,
  .loopback = false,
  .txWatermark = kUSART_TxFifo0,
  .rxWatermark = kUSART_RxFifo1,
  .enableRx = true,
  .enableTx = true,
  .enableHardwareFlowControl = false,
  .enableMode32k = false,
  .clockPolarity = kUSART_RxSampleOnFallingEdge,
  .enableContinuousSCLK = false
};
dma_handle_t UART0_FC0_RX_Handle;
dma_handle_t UART0_FC0_TX_Handle;
usart_dma_handle_t UART0_FC0_USART_DMA_Handle;

static void UART0_FC0_init(void) {
  USART_Init(UART0_FC0_PERIPHERAL, &UART0_FC0_config, UART0_FC0_CLOCK_SOURCE);
  /* Enable the DMA 4 channel in the DMA */
  DMA_EnableChannel(UART0_FC0_RX_DMA_BASEADDR, UART0_FC0_RX_DMA_CHANNEL);
  /* Create the DMA UART0_FC0_RX_Handle handle */
  DMA_CreateHandle(&UART0_FC0_RX_Handle, UART0_FC0_RX_DMA_BASEADDR, UART0_FC0_RX_DMA_CHANNEL);
  /* Enable the DMA 5 channel in the DMA */
  DMA_EnableChannel(UART0_FC0_TX_DMA_BASEADDR, UART0_FC0_TX_DMA_CHANNEL);
  /* Create the DMA UART0_FC0_TX_Handle handle */
  DMA_CreateHandle(&UART0_FC0_TX_Handle, UART0_FC0_TX_DMA_BASEADDR, UART0_FC0_TX_DMA_CHANNEL);
  /* Create the USART DMA handle */
  USART_TransferCreateHandleDMA(UART0_FC0_PERIPHERAL, &UART0_FC0_USART_DMA_Handle, NULL, NULL, &UART0_FC0_TX_Handle, &UART0_FC0_RX_Handle);
}

/***********************************************************************************************************************
 * UART1_FC1 initialization code
 **********************************************************************************************************************/
/* clang-format off */
/* TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
instance:
- name: 'UART1_FC1'
- type: 'flexcomm_usart'
- mode: 'dma'
- custom_name_enabled: 'true'
- type_id: 'flexcomm_usart_ed63debb5f147199906723fc49ad2e72'
- functional_group: 'BOARD_InitPeripherals'
- peripheral: 'FLEXCOMM1'
- config_sets:
  - dmaCfg:
    - dma_channels:
      - enable_rx_dma_channel: 'true'
      - dma_rx_channel:
        - DMA_source: 'kDma0RequestFlexcomm1Rx'
        - init_channel_priority: 'false'
        - dma_priority: 'kDMA_ChannelPriority0'
        - enable_custom_name: 'false'
      - enable_tx_dma_channel: 'true'
      - dma_tx_channel:
        - DMA_source: 'kDma0RequestFlexcomm1Tx'
        - init_channel_priority: 'false'
        - dma_priority: 'kDMA_ChannelPriority0'
        - enable_custom_name: 'false'
    - usart_dma_handle:
      - enable_custom_name: 'false'
      - init_callback: 'false'
      - callback_fcn: ''
      - user_data: ''
    - quick_selection: 'QuickSelection1'
  - usartConfig_t:
    - usartConfig:
      - clockSource: 'FXCOMFunctionClock'
      - clockSourceFreq: 'BOARD_BootClockPLL150M'
      - baudRate_Bps: '115200'
      - syncMode: 'kUSART_SyncModeDisabled'
      - parityMode: 'kUSART_ParityDisabled'
      - stopBitCount: 'kUSART_OneStopBit'
      - bitCountPerChar: 'kUSART_8BitsPerChar'
      - loopback: 'false'
      - txWatermark: 'kUSART_TxFifo0'
      - rxWatermark: 'kUSART_RxFifo1'
      - enableMatchAddress: 'false'
      - matchAddressConfig:
        - matchAddress: '0'
        - addressMode: 'automatic'
      - enableRx: 'true'
      - enableTx: 'true'
      - enableHardwareFlowControl: 'false'
      - enableRTS: 'false'
      - clockPolarity: 'kUSART_RxSampleOnFallingEdge'
      - enableContinuousSCLK: 'false'
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS **********/
/* clang-format on */
const usart_config_t UART1_FC1_config = {
  .baudRate_Bps = 115200UL,
  .syncMode = kUSART_SyncModeDisabled,
  .parityMode = kUSART_ParityDisabled,
  .stopBitCount = kUSART_OneStopBit,
  .bitCountPerChar = kUSART_8BitsPerChar,
  .loopback = false,
  .txWatermark = kUSART_TxFifo0,
  .rxWatermark = kUSART_RxFifo1,
  .enableRx = true,
  .enableTx = true,
  .enableHardwareFlowControl = false,
  .enableMode32k = false,
  .clockPolarity = kUSART_RxSampleOnFallingEdge,
  .enableContinuousSCLK = false
};
dma_handle_t UART1_FC1_RX_Handle;
dma_handle_t UART1_FC1_TX_Handle;
usart_dma_handle_t UART1_FC1_USART_DMA_Handle;

static void UART1_FC1_init(void) {
  USART_Init(UART1_FC1_PERIPHERAL, &UART1_FC1_config, UART1_FC1_CLOCK_SOURCE);
  /* Enable the DMA 6 channel in the DMA */
  DMA_EnableChannel(UART1_FC1_RX_DMA_BASEADDR, UART1_FC1_RX_DMA_CHANNEL);
  /* Create the DMA UART1_FC1_RX_Handle handle */
  DMA_CreateHandle(&UART1_FC1_RX_Handle, UART1_FC1_RX_DMA_BASEADDR, UART1_FC1_RX_DMA_CHANNEL);
  /* Enable the DMA 7 channel in the DMA */
  DMA_EnableChannel(UART1_FC1_TX_DMA_BASEADDR, UART1_FC1_TX_DMA_CHANNEL);
  /* Create the DMA UART1_FC1_TX_Handle handle */
  DMA_CreateHandle(&UART1_FC1_TX_Handle, UART1_FC1_TX_DMA_BASEADDR, UART1_FC1_TX_DMA_CHANNEL);
  /* Create the USART DMA handle */
  USART_TransferCreateHandleDMA(UART1_FC1_PERIPHERAL, &UART1_FC1_USART_DMA_Handle, NULL, NULL, &UART1_FC1_TX_Handle, &UART1_FC1_RX_Handle);
}

/***********************************************************************************************************************
 * ADC_FC3 initialization code
 **********************************************************************************************************************/
/* clang-format off */
/* TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
instance:
- name: 'ADC_FC3'
- type: 'flexcomm_spi'
- mode: 'SPI_Transfer'
- custom_name_enabled: 'true'
- type_id: 'flexcomm_spi_481dadba00035f986f31ed9ac95af181'
- functional_group: 'BOARD_InitPeripherals'
- peripheral: 'FLEXCOMM3'
- config_sets:
  - transferCfg:
    - transfer:
      - init_transfer: 'false'
      - transfer_cfg:
        - halfDuplex: 'false'
        - txDataBufferEnable: 'true'
        - rxDataBufferEnable: 'true'
        - dataSize: '10'
      - init_callback: 'false'
      - callback_fcn: ''
      - user_data: ''
  - fsl_spi:
    - spi_mode: 'kSPI_Master'
    - clockSource: 'FXCOMFunctionClock'
    - clockSourceFreq: 'BOARD_BootClockPLL150M'
    - spi_master_config:
      - enableLoopback: 'false'
      - enableMaster: 'true'
      - polarity: 'kSPI_ClockPolarityActiveLow'
      - phase: 'kSPI_ClockPhaseSecondEdge'
      - direction: 'kSPI_MsbFirst'
      - baudRate_Bps: '200000'
      - dataWidth: 'kSPI_Data8Bits'
      - sselNum: 'kSPI_Ssel2'
      - sselPol_set: ''
      - txWatermark: 'kSPI_TxFifo0'
      - rxWatermark: 'kSPI_RxFifo1'
      - delayConfig:
        - preDelay: '2'
        - postDelay: '1'
        - frameDelay: '0'
        - transferDelay: '0'
    - interrupt_priority:
      - IRQn: 'FLEXCOMM3_IRQn'
      - enable_priority: 'false'
      - priority: '0'
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS **********/
/* clang-format on */
const spi_master_config_t ADC_FC3_config = {
  .enableLoopback = false,
  .enableMaster = true,
  .polarity = kSPI_ClockPolarityActiveLow,
  .phase = kSPI_ClockPhaseSecondEdge,
  .direction = kSPI_MsbFirst,
  .baudRate_Bps = 200000UL,
  .dataWidth = kSPI_Data8Bits,
  .sselNum = kSPI_Ssel2,
  .sselPol = kSPI_SpolActiveAllLow,
  .txWatermark = kSPI_TxFifo0,
  .rxWatermark = kSPI_RxFifo1,
  .delayConfig = {
    .preDelay = 2U,
    .postDelay = 1U,
    .frameDelay = 0U,
    .transferDelay = 0U
  }
};
spi_master_handle_t ADC_FC3_handle;

static void ADC_FC3_init(void) {
  /* Initialization function */
  SPI_MasterInit(ADC_FC3_PERIPHERAL, &ADC_FC3_config, ADC_FC3_CLOCK_SOURCE);
  SPI_MasterTransferCreateHandle(ADC_FC3_PERIPHERAL, &ADC_FC3_handle, NULL, NULL);
}

/***********************************************************************************************************************
 * DIPSW_SPI initialization code
 **********************************************************************************************************************/
/* clang-format off */
/* TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
instance:
- name: 'DIPSW_SPI'
- type: 'flexcomm_spi'
- mode: 'SPI_Transfer'
- custom_name_enabled: 'true'
- type_id: 'flexcomm_spi_481dadba00035f986f31ed9ac95af181'
- functional_group: 'BOARD_InitPeripherals'
- peripheral: 'FLEXCOMM8'
- config_sets:
  - transferCfg:
    - transfer:
      - init_transfer: 'false'
      - transfer_cfg:
        - halfDuplex: 'false'
        - txDataBufferEnable: 'true'
        - rxDataBufferEnable: 'true'
        - dataSize: '10'
      - init_callback: 'false'
      - callback_fcn: ''
      - user_data: ''
  - fsl_spi:
    - spi_mode: 'kSPI_Master'
    - clockSource: 'FXCOMFunctionClock'
    - clockSourceFreq: 'BOARD_BootClockPLL150M'
    - spi_master_config:
      - enableLoopback: 'false'
      - enableMaster: 'true'
      - polarity: 'kSPI_ClockPolarityActiveLow'
      - phase: 'kSPI_ClockPhaseFirstEdge'
      - direction: 'kSPI_MsbFirst'
      - baudRate_Bps: '100000'
      - dataWidth: 'kSPI_Data8Bits'
      - sselNum: 'kSPI_Ssel1'
      - sselPol_set: 'kSPI_Spol1ActiveHigh'
      - txWatermark: 'kSPI_TxFifo0'
      - rxWatermark: 'kSPI_RxFifo1'
      - delayConfig:
        - preDelay: '1'
        - postDelay: '0'
        - frameDelay: '0'
        - transferDelay: '0'
    - interrupt_priority:
      - IRQn: 'FLEXCOMM8_IRQn'
      - enable_priority: 'false'
      - priority: '0'
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS **********/
/* clang-format on */
const spi_master_config_t DIPSW_SPI_config = {
  .enableLoopback = false,
  .enableMaster = true,
  .polarity = kSPI_ClockPolarityActiveLow,
  .phase = kSPI_ClockPhaseFirstEdge,
  .direction = kSPI_MsbFirst,
  .baudRate_Bps = 100000UL,
  .dataWidth = kSPI_Data8Bits,
  .sselNum = kSPI_Ssel1,
  .sselPol = kSPI_Spol1ActiveHigh,
  .txWatermark = kSPI_TxFifo0,
  .rxWatermark = kSPI_RxFifo1,
  .delayConfig = {
    .preDelay = 1U,
    .postDelay = 0U,
    .frameDelay = 0U,
    .transferDelay = 0U
  }
};
spi_master_handle_t DIPSW_SPI_handle;

static void DIPSW_SPI_init(void) {
  /* Initialization function */
  SPI_MasterInit(DIPSW_SPI_PERIPHERAL, &DIPSW_SPI_config, DIPSW_SPI_CLOCK_SOURCE);
  SPI_MasterTransferCreateHandle(DIPSW_SPI_PERIPHERAL, &DIPSW_SPI_handle, NULL, NULL);
}

/***********************************************************************************************************************
 * CJC_ADC0 initialization code
 **********************************************************************************************************************/
/* clang-format off */
/* TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
instance:
- name: 'CJC_ADC0'
- type: 'lpadc'
- mode: 'LPADC'
- custom_name_enabled: 'true'
- type_id: 'lpadc_ddcc12878b96237847ab78b571214e1c'
- functional_group: 'BOARD_InitPeripherals'
- peripheral: 'ADC0'
- config_sets:
  - fsl_lpadc:
    - lpadcConfig:
      - clockSource: 'AsynchronousFunctionClock'
      - clockSourceFreq: 'BOARD_BootClockPLL150M'
      - enableInDozeMode: 'true'
      - conversionAverageMode: 'kLPADC_ConversionAverage128'
      - offsetCalibration: 'yes'
      - autoCalibrate: 'true'
      - enableAnalogPreliminary: 'true'
      - powerUpDelay: '0x80'
      - referenceVoltageSource: 'kLPADC_ReferenceVoltageAlt3'
      - powerLevelMode: 'kLPADC_PowerLevelAlt4'
      - triggerPriorityPolicy: 'kLPADC_TriggerPriorityPreemptImmediately'
      - enableConvPause: 'false'
      - convPauseDelay: '0'
      - FIFO0Watermark: '0'
      - FIFO1Watermark: '1'
      - FIFO0WatermarkDMA: 'false'
      - FIFO1WatermarkDMA: 'false'
    - lpadcConvCommandConfig:
      - 0:
        - user_commandId: 'CJC0_Cmd'
        - commandId: '1'
        - chainedNextCommandNumber: '0'
        - sampleChannelMode: 'kLPADC_SampleChannelSingleEndSideA'
        - channelNumber: 'CH.3'
        - enableAutoChannelIncrement: 'false'
        - loopCount: '0'
        - hardwareAverageMode: 'kLPADC_HardwareAverageCount128'
        - sampleTimeMode: 'kLPADC_SampleTimeADCK131'
        - hardwareCompareMode: 'kLPADC_HardwareCompareDisabled'
        - hardwareCompareValueHigh: '0'
        - hardwareCompareValueLow: '0'
        - conversionResoultuionMode: 'kLPADC_ConversionResolutionHigh'
        - enableWaitTrigger: 'false'
      - 1:
        - user_commandId: 'CJC1_Cmd'
        - commandId: '2'
        - chainedNextCommandNumber: '0'
        - sampleChannelMode: 'kLPADC_SampleChannelSingleEndSideA'
        - channelNumber: 'CH.2'
        - enableAutoChannelIncrement: 'false'
        - loopCount: '0'
        - hardwareAverageMode: 'kLPADC_HardwareAverageCount128'
        - sampleTimeMode: 'kLPADC_SampleTimeADCK131'
        - hardwareCompareMode: 'kLPADC_HardwareCompareDisabled'
        - hardwareCompareValueHigh: '0'
        - hardwareCompareValueLow: '0'
        - conversionResoultuionMode: 'kLPADC_ConversionResolutionHigh'
        - enableWaitTrigger: 'false'
      - 2:
        - user_commandId: 'ChipTemp_Cmd'
        - commandId: '3'
        - chainedNextCommandNumber: '0'
        - sampleChannelMode: 'kLPADC_SampleChannelDiffBothSide'
        - channelNumber: 'CH.26A'
        - enableAutoChannelIncrement: 'false'
        - loopCount: '1'
        - hardwareAverageMode: 'kLPADC_HardwareAverageCount128'
        - sampleTimeMode: 'kLPADC_SampleTimeADCK131'
        - hardwareCompareMode: 'kLPADC_HardwareCompareDisabled'
        - hardwareCompareValueHigh: '0'
        - hardwareCompareValueLow: '0'
        - conversionResoultuionMode: 'kLPADC_ConversionResolutionHigh'
        - enableWaitTrigger: 'false'
    - lpadcConvTriggerConfig:
      - 0:
        - user_triggerId: 'CJC0_Trig'
        - triggerId: '0'
        - targetCommandId: '1'
        - delayPower: '0'
        - priority: 'false'
        - channelAFIFOSelect: '0'
        - channelBFIFOSelect: '0'
        - enableHardwareTrigger: 'false'
      - 1:
        - user_triggerId: 'CJC1_Trig'
        - triggerId: '1'
        - targetCommandId: '2'
        - delayPower: '0'
        - priority: 'false'
        - channelAFIFOSelect: '0'
        - channelBFIFOSelect: '0'
        - enableHardwareTrigger: 'false'
      - 2:
        - user_triggerId: 'ChipTemp_Trig'
        - triggerId: '2'
        - targetCommandId: '3'
        - delayPower: '0'
        - priority: 'false'
        - channelAFIFOSelect: '1'
        - channelBFIFOSelect: '1'
        - enableHardwareTrigger: 'false'
    - IRQ_cfg:
      - interrupt_type: 'kLPADC_FIFO0WatermarkInterruptEnable kLPADC_FIFO1WatermarkInterruptEnable'
      - enable_irq: 'true'
      - adc_interrupt:
        - IRQn: 'ADC0_IRQn'
        - enable_interrrupt: 'enabled'
        - enable_priority: 'false'
        - priority: '0'
        - enable_custom_name: 'false'
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS **********/
/* clang-format on */
const lpadc_config_t CJC_ADC0_config = {
  .enableInDozeMode = true,
  .conversionAverageMode = kLPADC_ConversionAverage128,
  .enableAnalogPreliminary = true,
  .powerUpDelay = 0x80UL,
  .referenceVoltageSource = kLPADC_ReferenceVoltageAlt3,
  .powerLevelMode = kLPADC_PowerLevelAlt4,
  .triggerPriorityPolicy = kLPADC_TriggerPriorityPreemptImmediately,
  .enableConvPause = false,
  .convPauseDelay = 0UL,
  .FIFO0Watermark = 0UL,
  .FIFO1Watermark = 1UL
};
lpadc_conv_command_config_t CJC_ADC0_commandsConfig[3] = {
  {
    .sampleChannelMode = kLPADC_SampleChannelSingleEndSideA,
    .channelNumber = 3U,
    .chainedNextCommandNumber = 0,
    .enableAutoChannelIncrement = false,
    .loopCount = 0UL,
    .hardwareAverageMode = kLPADC_HardwareAverageCount128,
    .sampleTimeMode = kLPADC_SampleTimeADCK131,
    .hardwareCompareMode = kLPADC_HardwareCompareDisabled,
    .hardwareCompareValueHigh = 0UL,
    .hardwareCompareValueLow = 0UL,
    .conversionResolutionMode = kLPADC_ConversionResolutionHigh,
    .enableWaitTrigger = false
  },
  {
    .sampleChannelMode = kLPADC_SampleChannelSingleEndSideA,
    .channelNumber = 2U,
    .chainedNextCommandNumber = 0,
    .enableAutoChannelIncrement = false,
    .loopCount = 0UL,
    .hardwareAverageMode = kLPADC_HardwareAverageCount128,
    .sampleTimeMode = kLPADC_SampleTimeADCK131,
    .hardwareCompareMode = kLPADC_HardwareCompareDisabled,
    .hardwareCompareValueHigh = 0UL,
    .hardwareCompareValueLow = 0UL,
    .conversionResolutionMode = kLPADC_ConversionResolutionHigh,
    .enableWaitTrigger = false
  },
  {
    .sampleChannelMode = kLPADC_SampleChannelDiffBothSide,
    .channelNumber = 26U,
    .chainedNextCommandNumber = 0,
    .enableAutoChannelIncrement = false,
    .loopCount = 1UL,
    .hardwareAverageMode = kLPADC_HardwareAverageCount128,
    .sampleTimeMode = kLPADC_SampleTimeADCK131,
    .hardwareCompareMode = kLPADC_HardwareCompareDisabled,
    .hardwareCompareValueHigh = 0UL,
    .hardwareCompareValueLow = 0UL,
    .conversionResolutionMode = kLPADC_ConversionResolutionHigh,
    .enableWaitTrigger = false
  }
};
lpadc_conv_trigger_config_t CJC_ADC0_triggersConfig[3] = {
  {
    .targetCommandId = 1,
    .delayPower = 0UL,
    .channelAFIFOSelect = 0,
    .channelBFIFOSelect = 0,
    .priority = 1,
    .enableHardwareTrigger = false
  },
  {
    .targetCommandId = 2,
    .delayPower = 0UL,
    .channelAFIFOSelect = 0,
    .channelBFIFOSelect = 0,
    .priority = 1,
    .enableHardwareTrigger = false
  },
  {
    .targetCommandId = 3,
    .delayPower = 0UL,
    .channelAFIFOSelect = 1,
    .channelBFIFOSelect = 1,
    .priority = 1,
    .enableHardwareTrigger = false
  }
};

static void CJC_ADC0_init(void) {
  /* Power up LDO for ADC */
  POWER_DisablePD(kPDRUNCFG_PD_LDOGPADC);
  /* Initialize LPADC converter */
  LPADC_Init(CJC_ADC0_PERIPHERAL, &CJC_ADC0_config);
  /* Perform offset calibration */
  LPADC_DoOffsetCalibration(CJC_ADC0_PERIPHERAL);
  /* Perform auto calibration */
  LPADC_DoAutoCalibration(CJC_ADC0_PERIPHERAL);
  /* Configure conversion command 1. */
  LPADC_SetConvCommandConfig(CJC_ADC0_PERIPHERAL, CJC_ADC0_CJC0_CMD, &CJC_ADC0_commandsConfig[0]);
  /* Configure conversion command 2. */
  LPADC_SetConvCommandConfig(CJC_ADC0_PERIPHERAL, CJC_ADC0_CJC1_CMD, &CJC_ADC0_commandsConfig[1]);
  /* Configure conversion command 3. */
  LPADC_SetConvCommandConfig(CJC_ADC0_PERIPHERAL, CJC_ADC0_CHIPTEMP_CMD, &CJC_ADC0_commandsConfig[2]);
  /* Configure trigger 0. */
  LPADC_SetConvTriggerConfig(CJC_ADC0_PERIPHERAL, CJC_ADC0_CJC0_TRIG, &CJC_ADC0_triggersConfig[0]);
  /* Configure trigger 1. */
  LPADC_SetConvTriggerConfig(CJC_ADC0_PERIPHERAL, CJC_ADC0_CJC1_TRIG, &CJC_ADC0_triggersConfig[1]);
  /* Configure trigger 2. */
  LPADC_SetConvTriggerConfig(CJC_ADC0_PERIPHERAL, CJC_ADC0_CHIPTEMP_TRIG, &CJC_ADC0_triggersConfig[2]);
  /* Enable interrupts from LPADC */
  LPADC_EnableInterrupts(CJC_ADC0_PERIPHERAL, (kLPADC_FIFO0WatermarkInterruptEnable | kLPADC_FIFO1WatermarkInterruptEnable));
  /* Enable interrupt ADC0_IRQn request in the NVIC. */
  EnableIRQ(CJC_ADC0_IRQN);
}

/***********************************************************************************************************************
 * DAC_FC5 initialization code
 **********************************************************************************************************************/
/* clang-format off */
/* TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
instance:
- name: 'DAC_FC5'
- type: 'flexcomm_spi'
- mode: 'SPI_Transfer'
- custom_name_enabled: 'true'
- type_id: 'flexcomm_spi_481dadba00035f986f31ed9ac95af181'
- functional_group: 'BOARD_InitPeripherals'
- peripheral: 'FLEXCOMM5'
- config_sets:
  - transferCfg:
    - transfer:
      - init_transfer: 'false'
      - transfer_cfg:
        - halfDuplex: 'false'
        - txDataBufferEnable: 'true'
        - rxDataBufferEnable: 'true'
        - dataSize: '10'
      - init_callback: 'false'
      - callback_fcn: ''
      - user_data: ''
  - fsl_spi:
    - spi_mode: 'kSPI_Master'
    - clockSource: 'FXCOMFunctionClock'
    - clockSourceFreq: 'BOARD_BootClockPLL150M'
    - spi_master_config:
      - enableLoopback: 'false'
      - enableMaster: 'true'
      - polarity: 'kSPI_ClockPolarityActiveLow'
      - phase: 'kSPI_ClockPhaseFirstEdge'
      - direction: 'kSPI_MsbFirst'
      - baudRate_Bps: '500000'
      - dataWidth: 'kSPI_Data8Bits'
      - sselNum: 'kSPI_Ssel1'
      - sselPol_set: ''
      - txWatermark: 'kSPI_TxFifo0'
      - rxWatermark: 'kSPI_RxFifo1'
      - delayConfig:
        - preDelay: '1'
        - postDelay: '0'
        - frameDelay: '0'
        - transferDelay: '0'
    - interrupt_priority:
      - IRQn: 'FLEXCOMM5_IRQn'
      - enable_priority: 'false'
      - priority: '0'
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS **********/
/* clang-format on */
const spi_master_config_t DAC_FC5_config = {
  .enableLoopback = false,
  .enableMaster = true,
  .polarity = kSPI_ClockPolarityActiveLow,
  .phase = kSPI_ClockPhaseFirstEdge,
  .direction = kSPI_MsbFirst,
  .baudRate_Bps = 500000UL,
  .dataWidth = kSPI_Data8Bits,
  .sselNum = kSPI_Ssel1,
  .sselPol = kSPI_SpolActiveAllLow,
  .txWatermark = kSPI_TxFifo0,
  .rxWatermark = kSPI_RxFifo1,
  .delayConfig = {
    .preDelay = 1U,
    .postDelay = 0U,
    .frameDelay = 0U,
    .transferDelay = 0U
  }
};
spi_master_handle_t DAC_FC5_handle;

static void DAC_FC5_init(void) {
  /* Initialization function */
  SPI_MasterInit(DAC_FC5_PERIPHERAL, &DAC_FC5_config, DAC_FC5_CLOCK_SOURCE);
  SPI_MasterTransferCreateHandle(DAC_FC5_PERIPHERAL, &DAC_FC5_handle, NULL, NULL);
}

/***********************************************************************************************************************
 * MEM_FC7 initialization code
 **********************************************************************************************************************/
/* clang-format off */
/* TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
instance:
- name: 'MEM_FC7'
- type: 'flexcomm_spi'
- mode: 'SPI_Transfer'
- custom_name_enabled: 'true'
- type_id: 'flexcomm_spi_481dadba00035f986f31ed9ac95af181'
- functional_group: 'BOARD_InitPeripherals'
- peripheral: 'FLEXCOMM7'
- config_sets:
  - transferCfg:
    - transfer:
      - init_transfer: 'false'
      - transfer_cfg:
        - halfDuplex: 'false'
        - txDataBufferEnable: 'true'
        - rxDataBufferEnable: 'true'
        - dataSize: '10'
      - init_callback: 'false'
      - callback_fcn: ''
      - user_data: ''
  - fsl_spi:
    - spi_mode: 'kSPI_Master'
    - clockSource: 'FXCOMFunctionClock'
    - clockSourceFreq: 'BOARD_BootClockPLL150M'
    - spi_master_config:
      - enableLoopback: 'false'
      - enableMaster: 'true'
      - polarity: 'kSPI_ClockPolarityActiveLow'
      - phase: 'kSPI_ClockPhaseSecondEdge'
      - direction: 'kSPI_MsbFirst'
      - baudRate_Bps: '500000'
      - dataWidth: 'kSPI_Data8Bits'
      - sselNum: 'kSPI_Ssel1'
      - sselPol_set: ''
      - txWatermark: 'kSPI_TxFifo0'
      - rxWatermark: 'kSPI_RxFifo1'
      - delayConfig:
        - preDelay: '2'
        - postDelay: '0'
        - frameDelay: '0'
        - transferDelay: '0'
    - interrupt_priority:
      - IRQn: 'FLEXCOMM7_IRQn'
      - enable_priority: 'false'
      - priority: '0'
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS **********/
/* clang-format on */
const spi_master_config_t MEM_FC7_config = {
  .enableLoopback = false,
  .enableMaster = true,
  .polarity = kSPI_ClockPolarityActiveLow,
  .phase = kSPI_ClockPhaseSecondEdge,
  .direction = kSPI_MsbFirst,
  .baudRate_Bps = 500000UL,
  .dataWidth = kSPI_Data8Bits,
  .sselNum = kSPI_Ssel1,
  .sselPol = kSPI_SpolActiveAllLow,
  .txWatermark = kSPI_TxFifo0,
  .rxWatermark = kSPI_RxFifo1,
  .delayConfig = {
    .preDelay = 2U,
    .postDelay = 0U,
    .frameDelay = 0U,
    .transferDelay = 0U
  }
};
spi_master_handle_t MEM_FC7_handle;

static void MEM_FC7_init(void) {
  /* Initialization function */
  SPI_MasterInit(MEM_FC7_PERIPHERAL, &MEM_FC7_config, MEM_FC7_CLOCK_SOURCE);
  SPI_MasterTransferCreateHandle(MEM_FC7_PERIPHERAL, &MEM_FC7_handle, NULL, NULL);
}

/***********************************************************************************************************************
 * COMM_CTIMER4 initialization code
 **********************************************************************************************************************/
/* clang-format off */
/* TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
instance:
- name: 'COMM_CTIMER4'
- type: 'ctimer'
- mode: 'Capture_Match'
- custom_name_enabled: 'true'
- type_id: 'ctimer_44573e4bbd77c18d33bceb2e7900a074'
- functional_group: 'BOARD_InitPeripherals'
- peripheral: 'CTIMER4'
- config_sets:
  - fsl_ctimer:
    - ctimerConfig:
      - mode: 'kCTIMER_TimerMode'
      - clockSource: 'FunctionClock'
      - clockSourceFreq: 'BOARD_BootClockPLL150M'
      - timerPrescaler: '100'
    - EnableTimerInInit: 'false'
    - matchChannels:
      - 0:
        - matchChannelPrefixId: 'Match_0'
        - matchChannel: 'kCTIMER_Match_1'
        - matchValueStr: '1ms'
        - enableCounterReset: 'true'
        - enableCounterStop: 'true'
        - outControl: 'kCTIMER_Output_NoAction'
        - outPinInitValue: 'low'
        - enableInterrupt: 'true'
    - captureChannels: []
    - interruptCallbackConfig:
      - interrupt:
        - IRQn: 'CTIMER4_IRQn'
        - enable_priority: 'false'
        - priority: '0'
      - callback: 'kCTIMER_SingleCallback'
      - singleCallback: 'COMM_TMOut_callback'
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS **********/
/* clang-format on */
const ctimer_config_t COMM_CTIMER4_config = {
  .mode = kCTIMER_TimerMode,
  .input = kCTIMER_Capture_0,
  .prescale = 99
};
const ctimer_match_config_t COMM_CTIMER4_Match_0_config = {
  .matchValue = 9,
  .enableCounterReset = true,
  .enableCounterStop = true,
  .outControl = kCTIMER_Output_NoAction,
  .outPinInitState = false,
  .enableInterrupt = true
};
/* Single callback functions definition */
ctimer_callback_t COMM_CTIMER4_callback[] = {COMM_TMOut_callback};

static void COMM_CTIMER4_init(void) {
  /* CTIMER4 peripheral initialization */
  CTIMER_Init(COMM_CTIMER4_PERIPHERAL, &COMM_CTIMER4_config);
  /* Match channel 1 of CTIMER4 peripheral initialization */
  CTIMER_SetupMatch(COMM_CTIMER4_PERIPHERAL, COMM_CTIMER4_MATCH_0_CHANNEL, &COMM_CTIMER4_Match_0_config);
  CTIMER_RegisterCallBack(COMM_CTIMER4_PERIPHERAL, COMM_CTIMER4_callback, kCTIMER_SingleCallback);
}

/***********************************************************************************************************************
 * CRC_ENGINE initialization code
 **********************************************************************************************************************/
/* clang-format off */
/* TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
instance:
- name: 'CRC_ENGINE'
- type: 'lpc_crc'
- mode: 'general'
- custom_name_enabled: 'false'
- type_id: 'lpc_crc_5f5f079056dd2a843b86fbb64c18c8cd'
- functional_group: 'BOARD_InitPeripherals'
- peripheral: 'CRC_ENGINE'
- config_sets:
  - fsl_crc:
    - crc_config:
      - polynomial: 'kCRC_Polynomial_CRC_16'
      - reverseIn: 'true'
      - complementIn: 'false'
      - reverseOut: 'true'
      - complementOut: 'false'
      - seed: '0xffff'
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS **********/
/* clang-format on */
const crc_config_t CRC_ENGINE_config = {
  .polynomial = kCRC_Polynomial_CRC_16,
  .reverseIn = true,
  .complementIn = false,
  .reverseOut = true,
  .complementOut = false,
  .seed = 0xFFFFUL
};

static void CRC_ENGINE_init(void) {
  CRC_Init(CRC_ENGINE_PERIPHERAL, &CRC_ENGINE_config);
}

/***********************************************************************************************************************
 * PINT initialization code
 **********************************************************************************************************************/
/* clang-format off */
/* TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
instance:
- name: 'PINT'
- type: 'pint'
- mode: 'interrupt_mode'
- custom_name_enabled: 'false'
- type_id: 'pint_cf4a806bb2a6c1ffced58ae2ed7b43af'
- functional_group: 'BOARD_InitPeripherals'
- peripheral: 'PINT'
- config_sets:
  - general:
    - interrupt_array:
      - 0:
        - interrupt_id: 'INT_0'
        - interrupt_selection: 'PINT.0'
        - interrupt_type: 'kPINT_PinIntEnableRiseEdge'
        - callback_function: 'drv_level_detect_callback'
        - enable_callback: 'true'
        - interrupt:
          - IRQn: 'PIN_INT0_IRQn'
          - enable_priority: 'false'
          - priority: '0'
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS **********/
/* clang-format on */

static void PINT_init(void) {
  /* PINT initiation  */
  PINT_Init(PINT_PERIPHERAL);
  /* PINT PINT.0 configuration */
  PINT_PinInterruptConfig(PINT_PERIPHERAL, PINT_INT_0, kPINT_PinIntEnableRiseEdge, drv_level_detect_callback);
  /* Enable PINT PINT.0 callback */
  PINT_EnableCallbackByIndex(PINT_PERIPHERAL, kPINT_PinInt0);
}

/***********************************************************************************************************************
 * PINT_CLK initialization code
 **********************************************************************************************************************/
/* clang-format off */
/* TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
instance:
- name: 'PINT_CLK'
- type: 'pint'
- mode: 'interrupt_mode'
- custom_name_enabled: 'true'
- type_id: 'pint_cf4a806bb2a6c1ffced58ae2ed7b43af'
- functional_group: 'BOARD_InitPeripherals'
- peripheral: 'PINT'
- config_sets:
  - general:
    - interrupt_array:
      - 0:
        - interrupt_id: 'INT_1'
        - interrupt_selection: 'PINT.1'
        - interrupt_type: 'kPINT_PinIntEnableRiseEdge'
        - callback_function: 'drv_internalbus_clk_callback'
        - enable_callback: 'true'
        - interrupt:
          - IRQn: 'PIN_INT1_IRQn'
          - enable_priority: 'false'
          - priority: '0'
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS **********/
/* clang-format on */

static void PINT_CLK_init(void) {
  /* PINT_CLK initiation  */
  PINT_Init(PINT_CLK_PERIPHERAL);
  /* PINT_CLK PINT.1 configuration */
  PINT_PinInterruptConfig(PINT_CLK_PERIPHERAL, PINT_CLK_INT_1, kPINT_PinIntEnableRiseEdge, drv_internalbus_clk_callback);
  /* Enable PINT_CLK PINT.1 callback */
  PINT_EnableCallbackByIndex(PINT_CLK_PERIPHERAL, kPINT_PinInt1);
}

/***********************************************************************************************************************
 * MRT0 initialization code
 **********************************************************************************************************************/
/* clang-format off */
/* TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
instance:
- name: 'MRT0'
- type: 'mrt'
- mode: 'general_config'
- custom_name_enabled: 'false'
- type_id: 'mrt_ec4ff9f008b2eee803e5f398b3b3325f'
- functional_group: 'BOARD_InitPeripherals'
- peripheral: 'MRT0'
- config_sets:
  - fsl_mrt:
    - mrtOperationMode: 'HSM'
    - clockSettingMRT:
      - clockSource: 'BusInterfaceClock'
      - clockSourceFreq: 'ClocksTool_DefaultInit'
    - mrtChannels: []
    - interruptVector:
      - enableInterrupt: 'false'
      - interrupt:
        - IRQn: 'MRT0_IRQn'
        - enable_interrrupt: 'enabled'
        - enable_priority: 'false'
        - priority: '0'
        - enable_custom_name: 'false'
    - quick_selection: 'default'
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS **********/
/* clang-format on */
const mrt_config_t MRT0_config = {
  .enableMultiTask = false
};

static void MRT0_init(void) {
  /* MRT0 peripheral initialization */
  MRT_Init(MRT0_PERIPHERAL, &MRT0_config);
}

/***********************************************************************************************************************
 * Initialization functions
 **********************************************************************************************************************/
static void BOARD_InitPeripherals_CommonPostInit(void)
{
  /* Enable interrupt FLEXCOMM0_IRQn request in the NVIC. */
  EnableIRQ(UART0_FC0_IRQN);
  /* Enable interrupt FLEXCOMM1_IRQn request in the NVIC. */
  EnableIRQ(UART1_FC1_IRQN);
}

void BOARD_InitPeripherals(void)
{
  /* Global initialization */
  DMA_Init(DMA0_DMA_BASEADDR);
  DMA_Init(DMA1_DMA_BASEADDR);

  /* Initialize components */
  WWDT_init();
  OUT4_CTIMER2_init();
  OUT1_CTIMER0_init();
  OUT2_CTIMER1_init();
  OUT3_CTIMER3_init();
  UART0_FC0_init();
  UART1_FC1_init();
  ADC_FC3_init();
  DIPSW_SPI_init();
  CJC_ADC0_init();
  DAC_FC5_init();
  MEM_FC7_init();
  COMM_CTIMER4_init();
  CRC_ENGINE_init();
  PINT_init();
  PINT_CLK_init();
  MRT0_init();
  /* Common post-initialization */
  BOARD_InitPeripherals_CommonPostInit();
}

/***********************************************************************************************************************
 * BOARD_InitBootPeripherals function
 **********************************************************************************************************************/
void BOARD_InitBootPeripherals(void)
{
  BOARD_InitPeripherals();
}
