/***********************************************************************************************************************
 * This file was generated by the MCUXpresso Config Tools. Any manual edits made to this file
 * will be overwritten if the respective MCUXpresso Config Tools is used to update this file.
 **********************************************************************************************************************/

#ifndef _PIN_MUX_H_
#define _PIN_MUX_H_

/*!
 * @addtogroup pin_mux
 * @{
 */

/***********************************************************************************************************************
 * API
 **********************************************************************************************************************/

#if defined(__cplusplus)
extern "C" {
#endif

/*!
 * @brief Calls initialization functions.
 *
 */
void BOARD_InitBootPins(void);

#define IOCON_PIO_DIGITAL_EN 0x0100u  /*!<@brief Enables digital function */
#define IOCON_PIO_FUNC1 0x01u         /*!<@brief Selects pin function 1 */
#define IOCON_PIO_INV_DI 0x00u        /*!<@brief Input function is not inverted */
#define IOCON_PIO_MODE_INACT 0x00u    /*!<@brief No addition pin function */
#define IOCON_PIO_OPENDRAIN_DI 0x00u  /*!<@brief Open drain is disabled */
#define IOCON_PIO_SLEW_STANDARD 0x00u /*!<@brief Standard mode, output slew rate control is enabled */
#define PIO1_0_DIGIMODE_DIGITAL 0x01u /*!<@brief Select Digital mode.: Enable Digital mode. Digital input is enabled. */
#define PIO1_0_FUNC_ALT0 0x00u        /*!<@brief Selects pin function.: Alternative connection 0. */

/*! @name FC0_RXD_SDA_MOSI_DATA (number 92), U11[14]/U22[14]/FC0_USART_RXD
  @{ */
/* @} */

/*! @name FC0_TXD_SCL_MISO_WS (number 94), U11[13]/U22[13]/FC0_USART_TXD
  @{ */
/* @} */

/*! @name PIO1_0 (number 11), J29/P1_0
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITDEBUG_UARTPINS_FC0_DIR_GPIO GPIO                /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITDEBUG_UARTPINS_FC0_DIR_GPIO_PIN_MASK (1U << 0U) /*!<@brief GPIO pin mask */
#define BOARD_INITDEBUG_UARTPINS_FC0_DIR_PORT 1U                  /*!<@brief PORT peripheral base pointer */
#define BOARD_INITDEBUG_UARTPINS_FC0_DIR_PIN 0U                   /*!<@brief PORT pin number */
#define BOARD_INITDEBUG_UARTPINS_FC0_DIR_PIN_MASK (1U << 0U)      /*!<@brief PORT pin mask */
                                                                  /* @} */

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_InitDEBUG_UARTPins(void); /* Function assigned for the Cortex-M33 */

/*!
 * @brief Select Digital mode.: Enable Digital mode. Digital input is enabled. */
#define PIO0_13_DIGIMODE_DIGITAL 0x01u
/*!
 * @brief Selects pin function.: Alternative connection 5. */
#define PIO0_13_FUNC_ALT5 0x05u
/*!
 * @brief Select Digital mode.: Enable Digital mode. Digital input is enabled. */
#define PIO0_14_DIGIMODE_DIGITAL 0x01u
/*!
 * @brief Selects pin function.: Alternative connection 0. */
#define PIO0_14_FUNC_ALT0 0x00u
/*!
 * @brief Select Digital mode.: Enable Digital mode. Digital input is enabled. */
#define PIO1_11_DIGIMODE_DIGITAL 0x01u
/*!
 * @brief Selects pin function.: Alternative connection 2. */
#define PIO1_11_FUNC_ALT2 0x02u

/*! @name PIO0_14 (number 72), J13[11]/J13[12]/J18[6]/JS4[2]/FC1_I2C_SCL
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITUART2PINS_FC1_DIR_GPIO GPIO                 /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITUART2PINS_FC1_DIR_GPIO_PIN_MASK (1U << 14U) /*!<@brief GPIO pin mask */
#define BOARD_INITUART2PINS_FC1_DIR_PORT 0U                   /*!<@brief PORT peripheral base pointer */
#define BOARD_INITUART2PINS_FC1_DIR_PIN 14U                   /*!<@brief PORT pin number */
#define BOARD_INITUART2PINS_FC1_DIR_PIN_MASK (1U << 14U)      /*!<@brief PORT pin mask */
                                                              /* @} */

/*!
 * @brief Route 3 UART pins: RXD, TXD, RTS; Route 5 Expand Interface GPIO pins.
 *
 */
void BOARD_InitUART2Pins(void); /* Function assigned for the Cortex-M33 */

/*!
 * @brief Analog switch is open (disabled) */
#define IOCON_PIO_ASW_DI 0x00u
/*!
 * @brief Enables digital function */
#define IOCON_PIO_DIGITAL_EN 0x0100u
/*!
 * @brief Selects pin function 6 */
#define IOCON_PIO_FUNC6 0x06u
/*!
 * @brief Input function is not inverted */
#define IOCON_PIO_INV_DI 0x00u
/*!
 * @brief Selects pull-down function */
#define IOCON_PIO_MODE_PULLDOWN 0x10u
/*!
 * @brief Selects pull-up function */
#define IOCON_PIO_MODE_PULLUP 0x20u
/*!
 * @brief Open drain is disabled */
#define IOCON_PIO_OPENDRAIN_DI 0x00u
/*!
 * @brief Standard mode, output slew rate control is enabled */
#define IOCON_PIO_SLEW_STANDARD 0x00u
/*!
 * @brief Select Digital mode.: Enable Digital mode. Digital input is enabled. */
#define PIO0_10_DIGIMODE_DIGITAL 0x01u
/*!
 * @brief Selects pin function.: Alternative connection 6. */
#define PIO0_10_FUNC_ALT6 0x06u

/*! @name SWCLK (number 13), J10[8]/U18[4]/N4M_SWDCLK
  @{ */
/* @} */

/*! @name SWDIO (number 12), J10[6]/U18[8]/N4M_SWDIO
  @{ */
/* @} */

/*! @name SWO (number 21), J9[1]/U18[12]/N4M_SWO
  @{ */
/* @} */

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_InitSWD_DEBUGPins(void); /* Function assigned for the Cortex-M33 */

/*!
 * @brief Select Digital mode.: Enable Digital mode. Digital input is enabled. */
#define PIO0_4_DIGIMODE_DIGITAL 0x01u
/*!
 * @brief Selects pin function.: Alternative connection 1. */
#define PIO0_4_FUNC_ALT1 0x01u
/*!
 * @brief Select Digital mode.: Enable Digital mode. Digital input is enabled. */
#define PIO1_27_DIGIMODE_DIGITAL 0x01u

/*! @name CAN0_TD (number 85), U26[3]/CAN_TXD
  @{ */
/* @} */

/*! @name CAN0_RD (number 86), J10[16]/U24[14]/FC3_SPI_SSEL0
  @{ */
/* @} */

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_InitCANPins(void); /* Function assigned for the Cortex-M33 */

/*!
 * @brief Select Digital mode.: Enable Digital mode. Digital input is enabled. */
#define PIO0_20_DIGIMODE_DIGITAL 0x01u
/*!
 * @brief Selects pin function.: Alternative connection 1. */
#define PIO0_20_FUNC_ALT1 0x01u
/*!
 * @brief Select Digital mode.: Enable Digital mode. Digital input is enabled. */
#define PIO0_21_DIGIMODE_DIGITAL 0x01u
/*!
 * @brief Selects pin function.: Alternative connection 1. */
#define PIO0_21_FUNC_ALT1 0x01u
/*!
 * @brief Select Digital mode.: Enable Digital mode. Digital input is enabled. */
#define PIO0_24_DIGIMODE_DIGITAL 0x01u
/*!
 * @brief Selects pin function.: Alternative connection 0. */
#define PIO0_24_FUNC_ALT0 0x00u
/*!
 * @brief Select Digital mode.: Enable Digital mode. Digital input is enabled. */
#define PIO0_28_DIGIMODE_DIGITAL 0x01u
/*!
 * @brief Selects pin function.: Alternative connection 0. */
#define PIO0_28_FUNC_ALT0 0x00u
/*!
 * @brief Select Digital mode.: Enable Digital mode. Digital input is enabled. */
#define PIO0_2_DIGIMODE_DIGITAL 0x01u
/*!
 * @brief Selects pin function.: Alternative connection 1. */
#define PIO0_2_FUNC_ALT1 0x01u
/*!
 * @brief Select Digital mode.: Enable Digital mode. Digital input is enabled. */
#define PIO0_3_DIGIMODE_DIGITAL 0x01u
/*!
 * @brief Selects pin function.: Alternative connection 1. */
#define PIO0_3_FUNC_ALT1 0x01u
/*!
 * @brief Select Digital mode.: Enable Digital mode. Digital input is enabled. */
#define PIO0_6_DIGIMODE_DIGITAL 0x01u
/*!
 * @brief Selects pin function.: Alternative connection 1. */
#define PIO0_6_FUNC_ALT1 0x01u
/*!
 * @brief Select Digital mode.: Enable Digital mode. Digital input is enabled. */
#define PIO0_9_DIGIMODE_DIGITAL 0x01u
/*!
 * @brief Selects pin function.: Alternative connection 1. */
#define PIO0_9_FUNC_ALT1 0x01u
/*!
 * @brief Select Digital mode.: Enable Digital mode. Digital input is enabled. */
#define PIO1_12_DIGIMODE_DIGITAL 0x01u
/*!
 * @brief Selects pin function.: Alternative connection 0. */
#define PIO1_12_FUNC_ALT0 0x00u
/*!
 * @brief Select Digital mode.: Enable Digital mode. Digital input is enabled. */
#define PIO1_24_DIGIMODE_DIGITAL 0x01u
/*!
 * @brief Selects pin function.: Alternative connection 5. */
#define PIO1_24_FUNC_ALT5 0x05u
/*!
 * @brief Select Digital mode.: Enable Digital mode. Digital input is enabled. */
#define PIO1_26_DIGIMODE_DIGITAL 0x01u
/*!
 * @brief Selects pin function.: Alternative connection 0. */
#define PIO1_26_FUNC_ALT0 0x00u

/*! @name FC3_CTS_SDA_SSEL0 (number 74), J19[2]/J9[9]/FC7_I2S_TX
  @{ */
/* @} */

/*! @name FC3_RTS_SCL_SSEL1 (number 76), U13[29]/J9[13]/FC7_I2S_BCLK
  @{ */
/* @} */

/*! @name FC3_SSEL2 (number 55), J24/PI00_9
  @{ */
/* @} */

/*! @name FC3_SSEL3 (number 3), J8[3]/J12[9]/J12[16]/ARD_MIK_FC2_USART_RXD
  @{ */
/* @} */

/*! @name PIO0_28 (number 66), U5[1]/FS_USB0_OCP#
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITEXTADCPINS_CV_SEL_0_GPIO GPIO                 /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITEXTADCPINS_CV_SEL_0_GPIO_PIN_MASK (1U << 28U) /*!<@brief GPIO pin mask */
#define BOARD_INITEXTADCPINS_CV_SEL_0_PORT 0U                   /*!<@brief PORT peripheral base pointer */
#define BOARD_INITEXTADCPINS_CV_SEL_0_PIN 28U                   /*!<@brief PORT pin number */
#define BOARD_INITEXTADCPINS_CV_SEL_0_PIN_MASK (1U << 28U)      /*!<@brief PORT pin mask */
                                                                /* @} */

/*! @name PIO1_12 (number 67), U5[3]/FS_USB0_PWR_EN#
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITEXTADCPINS_CV_SEL_1_GPIO GPIO                 /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITEXTADCPINS_CV_SEL_1_GPIO_PIN_MASK (1U << 12U) /*!<@brief GPIO pin mask */
#define BOARD_INITEXTADCPINS_CV_SEL_1_PORT 1U                   /*!<@brief PORT peripheral base pointer */
#define BOARD_INITEXTADCPINS_CV_SEL_1_PIN 12U                   /*!<@brief PORT pin number */
#define BOARD_INITEXTADCPINS_CV_SEL_1_PIN_MASK (1U << 12U)      /*!<@brief PORT pin mask */
                                                                /* @} */

/*! @name PIO1_26 (number 68), U12[11]/J12[13]/J12[17]/ACC_INT_EXP_P1_26
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITEXTADCPINS_CV_SEL_2_GPIO GPIO                 /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITEXTADCPINS_CV_SEL_2_GPIO_PIN_MASK (1U << 26U) /*!<@brief GPIO pin mask */
#define BOARD_INITEXTADCPINS_CV_SEL_2_PORT 1U                   /*!<@brief PORT peripheral base pointer */
#define BOARD_INITEXTADCPINS_CV_SEL_2_PIN 26U                   /*!<@brief PORT pin number */
#define BOARD_INITEXTADCPINS_CV_SEL_2_PIN_MASK (1U << 26U)      /*!<@brief PORT pin mask */
                                                                /* @} */

/*! @name PIO0_24 (number 70), J26/P0_24
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITEXTADCPINS_CV_SEL_3_GPIO GPIO                 /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITEXTADCPINS_CV_SEL_3_GPIO_PIN_MASK (1U << 24U) /*!<@brief GPIO pin mask */
#define BOARD_INITEXTADCPINS_CV_SEL_3_PORT 0U                   /*!<@brief PORT peripheral base pointer */
#define BOARD_INITEXTADCPINS_CV_SEL_3_PIN 24U                   /*!<@brief PORT pin number */
#define BOARD_INITEXTADCPINS_CV_SEL_3_PIN_MASK (1U << 24U)      /*!<@brief PORT pin mask */
                                                                /* @} */

/*!
 * @brief Use 4 AD7124 modules; Route 7 SPI pins: MOSI(d_out), MISO(d_in), SCK(clock), SSEL0~3; Route 4 GPIO pins.
 *
 */
void BOARD_InitExtADCPins(void); /* Function assigned for the Cortex-M33 */

/*!
 * @brief Select Digital mode.: Enable Digital mode. Digital input is enabled. */
#define PIO0_0_DIGIMODE_DIGITAL 0x01u
/*!
 * @brief Selects pin function.: Alternative connection 3. */
#define PIO0_0_FUNC_ALT3 0x03u
/*!
 * @brief Select Digital mode.: Enable Digital mode. Digital input is enabled. */
#define PIO0_18_DIGIMODE_DIGITAL 0x01u
/*!
 * @brief Selects pin function.: Alternative connection 3. */
#define PIO0_18_FUNC_ALT3 0x03u
/*!
 * @brief Select Digital mode.: Enable Digital mode. Digital input is enabled. */
#define PIO1_19_DIGIMODE_DIGITAL 0x01u
/*!
 * @brief Selects pin function.: Alternative connection 3. */
#define PIO1_19_FUNC_ALT3 0x03u
/*!
 * @brief Select Digital mode.: Enable Digital mode. Digital input is enabled. */
#define PIO1_22_DIGIMODE_DIGITAL 0x01u
/*!
 * @brief Selects pin function.: Alternative connection 3. */
#define PIO1_22_FUNC_ALT3 0x03u

/*! @name CTIMER2_MAT3 (number 41), U25[3]/CAN_RXD
  @{ */
/* @} */

/*! @name CTIMER0_MAT0 (number 54), J11[2]/J13[5]/ARD_CMP0_IN_A
  @{ */
/* @} */

/*! @name CTIMER3_MAT1 (number 58), J18[4]/ISP_P1_19
  @{ */
/* @} */

/*! @name CTIMER1_MAT0 (number 56), J11[1]/J12[19]/EXP_CMP0_IN_C
  @{ */
/* @} */

/*!
 * @brief Route 4 CTIMER_MATCH(pwm) pins.
 *
 */
void BOARD_InitPULSEPins(void); /* Function assigned for the Cortex-M33 */

/*!
 * @brief Select Digital mode.: Enable Digital mode. Digital input is enabled. */
#define PIO0_27_DIGIMODE_DIGITAL 0x01u
/*!
 * @brief Selects pin function.: Alternative connection 0. */
#define PIO0_27_FUNC_ALT0 0x00u
/*!
 * @brief Select Digital mode.: Enable Digital mode. Digital input is enabled. */
#define PIO0_7_DIGIMODE_DIGITAL 0x01u
/*!
 * @brief Selects pin function.: Alternative connection 3. */
#define PIO0_7_FUNC_ALT3 0x03u
/*!
 * @brief Select Digital mode.: Enable Digital mode. Digital input is enabled. */
#define PIO0_8_DIGIMODE_DIGITAL 0x01u
/*!
 * @brief Selects pin function.: Alternative connection 3. */
#define PIO0_8_FUNC_ALT3 0x03u
/*!
 * @brief Select Digital mode.: Enable Digital mode. Digital input is enabled. */
#define PIO1_15_DIGIMODE_DIGITAL 0x01u
/*!
 * @brief Selects pin function.: Alternative connection 0. */
#define PIO1_15_FUNC_ALT0 0x00u
/*!
 * @brief Select Digital mode.: Enable Digital mode. Digital input is enabled. */
#define PIO1_16_DIGIMODE_DIGITAL 0x01u
/*!
 * @brief Selects pin function.: Alternative connection 0. */
#define PIO1_16_FUNC_ALT0 0x00u

/*! @name PIO0_27 (number 27), J8[4]/J12[14]/ARD_MIK_FC2_USART_TXD
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITEXTDACPINS_SYNC_BAR_0_GPIO GPIO                 /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITEXTDACPINS_SYNC_BAR_0_GPIO_PIN_MASK (1U << 27U) /*!<@brief GPIO pin mask */
#define BOARD_INITEXTDACPINS_SYNC_BAR_0_PORT 0U                   /*!<@brief PORT peripheral base pointer */
#define BOARD_INITEXTDACPINS_SYNC_BAR_0_PIN 27U                   /*!<@brief PORT pin number */
#define BOARD_INITEXTDACPINS_SYNC_BAR_0_PIN_MASK (1U << 27U)      /*!<@brief PORT pin mask */
                                                                  /* @} */

/*! @name PIO1_15 (number 82), J3[4]/U6[3]/J12[11]/FS_USB0_ID
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITEXTDACPINS_SYNC_BAR_1_GPIO GPIO                 /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITEXTDACPINS_SYNC_BAR_1_GPIO_PIN_MASK (1U << 15U) /*!<@brief GPIO pin mask */
#define BOARD_INITEXTDACPINS_SYNC_BAR_1_PORT 1U                   /*!<@brief PORT peripheral base pointer */
#define BOARD_INITEXTDACPINS_SYNC_BAR_1_PIN 15U                   /*!<@brief PORT pin number */
#define BOARD_INITEXTDACPINS_SYNC_BAR_1_PIN_MASK (1U << 15U)      /*!<@brief PORT pin mask */
                                                                  /* @} */

/*! @name PIO1_16 (number 87), J12[18]/J13[4]/EXP_P1_16
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITEXTDACPINS_CLR_BAR_GPIO GPIO                 /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITEXTDACPINS_CLR_BAR_GPIO_PIN_MASK (1U << 16U) /*!<@brief GPIO pin mask */
#define BOARD_INITEXTDACPINS_CLR_BAR_PORT 1U                   /*!<@brief PORT peripheral base pointer */
#define BOARD_INITEXTDACPINS_CLR_BAR_PIN 16U                   /*!<@brief PORT pin number */
#define BOARD_INITEXTDACPINS_CLR_BAR_PIN_MASK (1U << 16U)      /*!<@brief PORT pin mask */
                                                               /* @} */

/*!
 * @brief Use 2 2-CH DAC modules; Route 5 pins: MOSI(data), SCK(clock), SSEL(/SYNC), GPIO0(/CLR), GPIO1(/LDAC)
 *
 */
void BOARD_InitExtDACPins(void); /* Function assigned for the Cortex-M33 */

/*!
 * @brief Select Digital mode.: Enable Digital mode. Digital input is enabled. */
#define PIO0_16_DIGIMODE_DIGITAL 0x01u
/*!
 * @brief Selects pin function.: Alternative connection 0. */
#define PIO0_16_FUNC_ALT0 0x00u
/*!
 * @brief Select Digital mode.: Enable Digital mode. Digital input is enabled. */
#define PIO0_19_DIGIMODE_DIGITAL 0x01u
/*!
 * @brief Selects pin function.: Alternative connection 0. */
#define PIO0_19_FUNC_ALT0 0x00u
/*!
 * @brief Select Digital mode.: Enable Digital mode. Digital input is enabled. */
#define PIO0_23_DIGIMODE_DIGITAL 0x01u
/*!
 * @brief Selects pin function.: Alternative connection 0. */
#define PIO0_23_FUNC_ALT0 0x00u
/*!
 * @brief Select Digital mode.: Enable Digital mode. Digital input is enabled. */
#define PIO0_25_DIGIMODE_DIGITAL 0x01u
/*!
 * @brief Selects pin function.: Alternative connection 0. */
#define PIO0_25_FUNC_ALT0 0x00u
/*!
 * @brief Select Digital mode.: Enable Digital mode. Digital input is enabled. */
#define PIO0_26_DIGIMODE_DIGITAL 0x01u
/*!
 * @brief Selects pin function.: Alternative connection 0. */
#define PIO0_26_FUNC_ALT0 0x00u
/*!
 * @brief Select Digital mode.: Enable Digital mode. Digital input is enabled. */
#define PIO1_25_DIGIMODE_DIGITAL 0x01u
/*!
 * @brief Selects pin function.: Alternative connection 0. */
#define PIO1_25_FUNC_ALT0 0x00u
/*!
 * @brief Select Digital mode.: Enable Digital mode. Digital input is enabled. */
#define PIO1_8_DIGIMODE_DIGITAL 0x01u
/*!
 * @brief Selects pin function.: Alternative connection 0. */
#define PIO1_8_FUNC_ALT0 0x00u
/*!
 * @brief Select Digital mode.: Enable Digital mode. Digital input is enabled. */
#define PIO1_9_DIGIMODE_DIGITAL 0x01u
/*!
 * @brief Selects pin function.: Alternative connection 0. */
#define PIO1_9_FUNC_ALT0 0x00u

/*! @name PIO1_9 (number 10), SW3/J12[2]/ARD_BTN_USR_P1_9
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITDIOPINS_DI0_GPIO GPIO                /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITDIOPINS_DI0_GPIO_PIN_MASK (1U << 9U) /*!<@brief GPIO pin mask */
#define BOARD_INITDIOPINS_DI0_PORT 1U                  /*!<@brief PORT peripheral base pointer */
#define BOARD_INITDIOPINS_DI0_PIN 9U                   /*!<@brief PORT pin number */
#define BOARD_INITDIOPINS_DI0_PIN_MASK (1U << 9U)      /*!<@brief PORT pin mask */
                                                       /* @} */

/*! @name PIO0_16 (number 14), J7[1]/J13[1]/JP4[1]/ARD_MIK_ADC0_8_N
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITDIOPINS_DI1_GPIO GPIO                 /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITDIOPINS_DI1_GPIO_PIN_MASK (1U << 16U) /*!<@brief GPIO pin mask */
#define BOARD_INITDIOPINS_DI1_PORT 0U                   /*!<@brief PORT peripheral base pointer */
#define BOARD_INITDIOPINS_DI1_PIN 16U                   /*!<@brief PORT pin number */
#define BOARD_INITDIOPINS_DI1_PIN_MASK (1U << 16U)      /*!<@brief PORT pin mask */
                                                        /* @} */

/*! @name PIO0_23 (number 20), J13[3]/JP4[3]/ARD_ADC0_0_P
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITDIOPINS_DI2_GPIO GPIO                 /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITDIOPINS_DI2_GPIO_PIN_MASK (1U << 23U) /*!<@brief GPIO pin mask */
#define BOARD_INITDIOPINS_DI2_PORT 0U                   /*!<@brief PORT peripheral base pointer */
#define BOARD_INITDIOPINS_DI2_PIN 23U                   /*!<@brief PORT pin number */
#define BOARD_INITDIOPINS_DI2_PIN_MASK (1U << 23U)      /*!<@brief PORT pin mask */
                                                        /* @} */

/*! @name PIO1_8 (number 24), J9[20]/ARD_P1_8
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITDIOPINS_DI3_GPIO GPIO                /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITDIOPINS_DI3_GPIO_PIN_MASK (1U << 8U) /*!<@brief GPIO pin mask */
#define BOARD_INITDIOPINS_DI3_PORT 1U                  /*!<@brief PORT peripheral base pointer */
#define BOARD_INITDIOPINS_DI3_PIN 8U                   /*!<@brief PORT pin number */
#define BOARD_INITDIOPINS_DI3_PIN_MASK (1U << 8U)      /*!<@brief PORT pin mask */
                                                       /* @} */

/*! @name PIO1_25 (number 77), J9[15]/J12[5]/I2S_IRQ
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITDIOPINS_DO3_GPIO GPIO                 /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITDIOPINS_DO3_GPIO_PIN_MASK (1U << 25U) /*!<@brief GPIO pin mask */
#define BOARD_INITDIOPINS_DO3_PORT 1U                   /*!<@brief PORT peripheral base pointer */
#define BOARD_INITDIOPINS_DO3_PIN 25U                   /*!<@brief PORT pin number */
#define BOARD_INITDIOPINS_DO3_PIN_MASK (1U << 25U)      /*!<@brief PORT pin mask */
                                                        /* @} */

/*! @name PIO0_25 (number 79), J27/P0_25
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITDIOPINS_DO2_GPIO GPIO                 /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITDIOPINS_DO2_GPIO_PIN_MASK (1U << 25U) /*!<@brief GPIO pin mask */
#define BOARD_INITDIOPINS_DO2_PORT 0U                   /*!<@brief PORT peripheral base pointer */
#define BOARD_INITDIOPINS_DO2_PIN 25U                   /*!<@brief PORT pin number */
#define BOARD_INITDIOPINS_DO2_PIN_MASK (1U << 25U)      /*!<@brief PORT pin mask */
                                                        /* @} */

/*! @name PIO0_19 (number 90), U13[30]/J9[11]/FC7_I2S_WS
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITDIOPINS_DO0_GPIO GPIO                 /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITDIOPINS_DO0_GPIO_PIN_MASK (1U << 19U) /*!<@brief GPIO pin mask */
#define BOARD_INITDIOPINS_DO0_PORT 0U                   /*!<@brief PORT peripheral base pointer */
#define BOARD_INITDIOPINS_DO0_PIN 19U                   /*!<@brief PORT pin number */
#define BOARD_INITDIOPINS_DO0_PIN_MASK (1U << 19U)      /*!<@brief PORT pin mask */
                                                        /* @} */

/*! @name PIO0_26 (number 60), J7[6]/J9[14]/ARD_MIK_HSSPI_MOSI
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITDIOPINS_DO1_GPIO GPIO                 /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITDIOPINS_DO1_GPIO_PIN_MASK (1U << 26U) /*!<@brief GPIO pin mask */
#define BOARD_INITDIOPINS_DO1_PORT 0U                   /*!<@brief PORT peripheral base pointer */
#define BOARD_INITDIOPINS_DO1_PIN 26U                   /*!<@brief PORT pin number */
#define BOARD_INITDIOPINS_DO1_PIN_MASK (1U << 26U)      /*!<@brief PORT pin mask */
                                                        /* @} */

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_InitDIOPins(void); /* Function assigned for the Cortex-M33 */

/*!
 * @brief Analog switch input control.: Analog switch is closed. (enable) */
#define PIO0_15_ASW_ENABLE 0x01u
/*!
 * @brief Select Digital mode.: Disable digital mode. Digital input set to 0. */
#define PIO0_15_DIGIMODE_ANALOG 0x00u
/*!
 * @brief Selects pin function.: Alternative connection 0. */
#define PIO0_15_FUNC_ALT0 0x00u
/*!
 * @brief
 * Selects function mode (on-chip pull-up/pull-down resistor control).
 * : Inactive.
 * Inactive (no pull-down/pull-up resistor enabled).
 */
#define PIO0_15_MODE_INACTIVE 0x00u
/*!
 * @brief Analog switch input control.: Analog switch is closed. (enable) */
#define PIO0_31_ASW_ENABLE 0x01u
/*!
 * @brief Select Digital mode.: Disable digital mode. Digital input set to 0. */
#define PIO0_31_DIGIMODE_ANALOG 0x00u
/*!
 * @brief Selects pin function.: Alternative connection 0. */
#define PIO0_31_FUNC_ALT0 0x00u
/*!
 * @brief
 * Selects function mode (on-chip pull-up/pull-down resistor control).
 * : Inactive.
 * Inactive (no pull-down/pull-up resistor enabled).
 */
#define PIO0_31_MODE_INACTIVE 0x00u

/*!
 * @brief Route 2 ADC0 pins.
 *
 */
void BOARD_InitCJCPins(void); /* Function assigned for the Cortex-M33 */

/*!
 * @brief Select Digital mode.: Enable Digital mode. Digital input is enabled. */
#define PIO1_20_DIGIMODE_DIGITAL 0x01u
/*!
 * @brief Selects pin function.: Alternative connection 1. */
#define PIO1_20_FUNC_ALT1 0x01u
/*!
 * @brief Select Digital mode.: Enable Digital mode. Digital input is enabled. */
#define PIO1_28_DIGIMODE_DIGITAL 0x01u
/*!
 * @brief Selects pin function.: Alternative connection 1. */
#define PIO1_28_FUNC_ALT1 0x01u
/*!
 * @brief Select Digital mode.: Enable Digital mode. Digital input is enabled. */
#define PIO1_29_DIGIMODE_DIGITAL 0x01u
/*!
 * @brief Selects pin function.: Alternative connection 1. */
#define PIO1_29_FUNC_ALT1 0x01u
/*!
 * @brief Select Digital mode.: Enable Digital mode. Digital input is enabled. */
#define PIO1_30_DIGIMODE_DIGITAL 0x01u
/*!
 * @brief Selects pin function.: Alternative connection 1. */
#define PIO1_30_FUNC_ALT1 0x01u

/*! @name FC7_RTS_SCL_SSEL1 (number 4), U12[4]/U13[2]/J8[5]/J9[2]/FC4_I2C_SCL
  @{ */
/* @} */

/*!
 * @brief Route 3 SPI pins: MOSI(d_out), MISO(d_in), SCK(clock).
 *
 */
void BOARD_InitExtMEMPins(void); /* Function assigned for the Cortex-M33 */

/*!
 * @brief Select Digital mode.: Enable Digital mode. Digital input is enabled. */
#define PIO0_22_DIGIMODE_DIGITAL 0x01u
/*!
 * @brief Selects pin function.: Alternative connection 7. */
#define PIO0_22_FUNC_ALT7 0x07u

/*! @name USB0_DM (number 98), J3[2]/FS_USB0_DN
  @{ */
/* @} */

/*! @name USB0_DP (number 97), J3[3]/FS_USB0_DP
  @{ */
/* @} */

/*! @name USB0_VBUS (number 78), USB0_VBUS
  @{ */
/* @} */

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_InitUSBPins(void); /* Function assigned for the Cortex-M33 */

#define PIO1_4_DIGIMODE_DIGITAL 0x01u /*!<@brief Select Digital mode.: Enable Digital mode. Digital input is enabled. */
#define PIO1_4_FUNC_ALT0 0x00u        /*!<@brief Selects pin function.: Alternative connection 0. */
#define PIO1_6_DIGIMODE_DIGITAL 0x01u /*!<@brief Select Digital mode.: Enable Digital mode. Digital input is enabled. */
#define PIO1_6_FUNC_ALT0 0x00u        /*!<@brief Selects pin function.: Alternative connection 0. */
#define PIO1_7_DIGIMODE_DIGITAL 0x01u /*!<@brief Select Digital mode.: Enable Digital mode. Digital input is enabled. */
#define PIO1_7_FUNC_ALT0 0x00u        /*!<@brief Selects pin function.: Alternative connection 0. */

/*! @name PIO1_4 (number 1), Q5[G1]/J12[6]/ARD_LEDR_PWM
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITLEDSPINS_LED_ERR_GPIO GPIO                /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITLEDSPINS_LED_ERR_GPIO_PIN_MASK (1U << 4U) /*!<@brief GPIO pin mask */
#define BOARD_INITLEDSPINS_LED_ERR_PORT 1U                  /*!<@brief PORT peripheral base pointer */
#define BOARD_INITLEDSPINS_LED_ERR_PIN 4U                   /*!<@brief PORT pin number */
#define BOARD_INITLEDSPINS_LED_ERR_PIN_MASK (1U << 4U)      /*!<@brief PORT pin mask */
                                                            /* @} */

/*! @name PIO1_6 (number 5), Q4[G1]/J12[10]/ARD_LEDB_PWM
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITLEDSPINS_LED_COM_GPIO GPIO                /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITLEDSPINS_LED_COM_GPIO_PIN_MASK (1U << 6U) /*!<@brief GPIO pin mask */
#define BOARD_INITLEDSPINS_LED_COM_PORT 1U                  /*!<@brief PORT peripheral base pointer */
#define BOARD_INITLEDSPINS_LED_COM_PIN 6U                   /*!<@brief PORT pin number */
#define BOARD_INITLEDSPINS_LED_COM_PIN_MASK (1U << 6U)      /*!<@brief PORT pin mask */
                                                            /* @} */

/*! @name PIO1_7 (number 9), Q4[G2]/J12[8]/ARD_LEDG_PWM
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITLEDSPINS_LED_RUN_GPIO GPIO                /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITLEDSPINS_LED_RUN_GPIO_PIN_MASK (1U << 7U) /*!<@brief GPIO pin mask */
#define BOARD_INITLEDSPINS_LED_RUN_PORT 1U                  /*!<@brief PORT peripheral base pointer */
#define BOARD_INITLEDSPINS_LED_RUN_PIN 7U                   /*!<@brief PORT pin number */
#define BOARD_INITLEDSPINS_LED_RUN_PIN_MASK (1U << 7U)      /*!<@brief PORT pin mask */
                                                            /* @} */

/*!
 * @brief Route default RGB pins.
 *
 */
void BOARD_InitLEDsPins(void); /* Function assigned for the Cortex-M33 */

#define PIO1_1_DIGIMODE_DIGITAL 0x01u /*!<@brief Select Digital mode.: Enable Digital mode. Digital input is enabled. */
#define PIO1_1_FUNC_ALT5 0x05u        /*!<@brief Selects pin function.: Alternative connection 5. */
#define PIO1_2_DIGIMODE_DIGITAL 0x01u /*!<@brief Select Digital mode.: Enable Digital mode. Digital input is enabled. */
#define PIO1_2_FUNC_ALT6 0x06u        /*!<@brief Selects pin function.: Alternative connection 6. */
#define PIO1_3_DIGIMODE_DIGITAL 0x01u /*!<@brief Select Digital mode.: Enable Digital mode. Digital input is enabled. */
#define PIO1_3_FUNC_ALT6 0x06u        /*!<@brief Selects pin function.: Alternative connection 6. */

/*!
 * @brief Route 8 GPIO input pins.
 *
 */
void BOARD_InitDipSWPins(void); /* Function assigned for the Cortex-M33 */

/*!
 * @brief Select Digital mode.: Enable Digital mode. Digital input is enabled. */
#define PIO0_17_DIGIMODE_DIGITAL 0x01u
/*!
 * @brief Selects pin function.: Alternative connection 0. */
#define PIO0_17_FUNC_ALT0 0x00u
/*!
 * @brief Select Digital mode.: Enable Digital mode. Digital input is enabled. */
#define PIO0_1_DIGIMODE_DIGITAL 0x01u
/*!
 * @brief Selects pin function.: Alternative connection 0. */
#define PIO0_1_FUNC_ALT0 0x00u
/*!
 * @brief Select Digital mode.: Enable Digital mode. Digital input is enabled. */
#define PIO1_13_DIGIMODE_DIGITAL 0x01u
/*!
 * @brief Selects pin function.: Alternative connection 0. */
#define PIO1_13_FUNC_ALT0 0x00u
/*!
 * @brief Select Digital mode.: Enable Digital mode. Digital input is enabled. */
#define PIO1_18_DIGIMODE_DIGITAL 0x01u
/*!
 * @brief Selects pin function.: Alternative connection 0. */
#define PIO1_18_FUNC_ALT0 0x00u

/*! @name PIO1_13 (number 2), J18[2]/J9[19]/FC6_I2S_RX
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITROTARYSWPINS_RR_SW_1_GPIO GPIO                 /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITROTARYSWPINS_RR_SW_1_GPIO_PIN_MASK (1U << 13U) /*!<@brief GPIO pin mask */
#define BOARD_INITROTARYSWPINS_RR_SW_1_PORT 1U                   /*!<@brief PORT peripheral base pointer */
#define BOARD_INITROTARYSWPINS_RR_SW_1_PIN 13U                   /*!<@brief PORT pin number */
#define BOARD_INITROTARYSWPINS_RR_SW_1_PIN_MASK (1U << 13U)      /*!<@brief PORT pin mask */
                                                                 /* @} */

/*! @name PIO0_1 (number 7), J11[3]/J12[1]/EXP_CMP0_OUT
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITROTARYSWPINS_RR_SW_4_GPIO GPIO                /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITROTARYSWPINS_RR_SW_4_GPIO_PIN_MASK (1U << 1U) /*!<@brief GPIO pin mask */
#define BOARD_INITROTARYSWPINS_RR_SW_4_PORT 0U                  /*!<@brief PORT peripheral base pointer */
#define BOARD_INITROTARYSWPINS_RR_SW_4_PIN 1U                   /*!<@brief PORT pin number */
#define BOARD_INITROTARYSWPINS_RR_SW_4_PIN_MASK (1U << 1U)      /*!<@brief PORT pin mask */
                                                                /* @} */

/*! @name PIO0_17 (number 8), J25/P0_17
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITROTARYSWPINS_RR_SW_8_GPIO GPIO                 /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITROTARYSWPINS_RR_SW_8_GPIO_PIN_MASK (1U << 17U) /*!<@brief GPIO pin mask */
#define BOARD_INITROTARYSWPINS_RR_SW_8_PORT 0U                   /*!<@brief PORT peripheral base pointer */
#define BOARD_INITROTARYSWPINS_RR_SW_8_PIN 17U                   /*!<@brief PORT pin number */
#define BOARD_INITROTARYSWPINS_RR_SW_8_PIN_MASK (1U << 17U)      /*!<@brief PORT pin mask */
                                                                 /* @} */

/*! @name PIO1_18 (number 64), SW1/J8[2]/J12[15]/MIK_EXP_BTN_WK
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITROTARYSWPINS_RR_SW_2_GPIO GPIO                 /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITROTARYSWPINS_RR_SW_2_GPIO_PIN_MASK (1U << 18U) /*!<@brief GPIO pin mask */
#define BOARD_INITROTARYSWPINS_RR_SW_2_PORT 1U                   /*!<@brief PORT peripheral base pointer */
#define BOARD_INITROTARYSWPINS_RR_SW_2_PIN 18U                   /*!<@brief PORT pin number */
#define BOARD_INITROTARYSWPINS_RR_SW_2_PIN_MASK (1U << 18U)      /*!<@brief PORT pin mask */
                                                                 /* @} */

/*!
 * @brief Route 4 GPIO input pins.
 *
 */
void BOARD_InitRotarySWPins(void); /* Function assigned for the Cortex-M33 */

/*!
 * @brief Select Digital mode.: Enable Digital mode. Digital input is enabled. */
#define PIO1_31_DIGIMODE_DIGITAL 0x01u
/*!
 * @brief Selects pin function.: Alternative connection 0. */
#define PIO1_31_FUNC_ALT0 0x00u

/*! @name PIO1_31 (number 91), J13[7]/J13[8]/U13[28]/I2S_MCLK
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITLVPINS_LV_GPIO GPIO                 /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITLVPINS_LV_GPIO_PIN_MASK (1U << 31U) /*!<@brief GPIO pin mask */
#define BOARD_INITLVPINS_LV_PORT 1U                   /*!<@brief PORT peripheral base pointer */
#define BOARD_INITLVPINS_LV_PIN 31U                   /*!<@brief PORT pin number */
#define BOARD_INITLVPINS_LV_PIN_MASK (1U << 31U)      /*!<@brief PORT pin mask */
                                                      /* @} */

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_InitLVPins(void); /* Function assigned for the Cortex-M33 */

#define IOCON_PIO_ASW_DI 0x00u        /*!<@brief Analog switch is open (disabled) */
#define IOCON_PIO_DIGITAL_EN 0x0100u  /*!<@brief Enables digital function */
#define IOCON_PIO_FUNC0 0x00u         /*!<@brief Selects pin function 0 */
#define IOCON_PIO_INV_DI 0x00u        /*!<@brief Input function is not inverted */
#define IOCON_PIO_MODE_PULLUP 0x20u   /*!<@brief Selects pull-up function */
#define IOCON_PIO_OPENDRAIN_DI 0x00u  /*!<@brief Open drain is disabled */
#define IOCON_PIO_SLEW_STANDARD 0x00u /*!<@brief Standard mode, output slew rate control is enabled */

/*! @name PIO1_18 (number 64), SW1/J8[2]/J12[15]/MIK_EXP_BTN_WK
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITBUTTONSPINS_WAKEUP_GPIO GPIO                 /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITBUTTONSPINS_WAKEUP_GPIO_PIN_MASK (1U << 18U) /*!<@brief GPIO pin mask */
#define BOARD_INITBUTTONSPINS_WAKEUP_PORT 1U                   /*!<@brief PORT peripheral base pointer */
#define BOARD_INITBUTTONSPINS_WAKEUP_PIN 18U                   /*!<@brief PORT pin number */
#define BOARD_INITBUTTONSPINS_WAKEUP_PIN_MASK (1U << 18U)      /*!<@brief PORT pin mask */
                                                               /* @} */

/*! @name PIO1_9 (number 10), SW3/J12[2]/ARD_BTN_USR_P1_9
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITBUTTONSPINS_USR_GPIO GPIO                /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITBUTTONSPINS_USR_GPIO_PIN_MASK (1U << 9U) /*!<@brief GPIO pin mask */
#define BOARD_INITBUTTONSPINS_USR_PORT 1U                  /*!<@brief PORT peripheral base pointer */
#define BOARD_INITBUTTONSPINS_USR_PIN 9U                   /*!<@brief PORT pin number */
#define BOARD_INITBUTTONSPINS_USR_PIN_MASK (1U << 9U)      /*!<@brief PORT pin mask */
                                                           /* @} */

/*! @name RESETN (number 32), SW2/J7[2]/J10[9]/J10[10]/U18[16]/N4M_RESET#
  @{ */
/* @} */

/*! @name PIO0_5 (number 88), J9[7]/J17[7]/J18[2]/SW4/JS3[1]/U22[11]/N4M_ISP_MODE
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITBUTTONSPINS_ISP_GPIO GPIO                /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITBUTTONSPINS_ISP_GPIO_PIN_MASK (1U << 5U) /*!<@brief GPIO pin mask */
#define BOARD_INITBUTTONSPINS_ISP_PORT 0U                  /*!<@brief PORT peripheral base pointer */
#define BOARD_INITBUTTONSPINS_ISP_PIN 5U                   /*!<@brief PORT pin number */
#define BOARD_INITBUTTONSPINS_ISP_PIN_MASK (1U << 5U)      /*!<@brief PORT pin mask */
                                                           /* @} */

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_InitBUTTONsPins(void); /* Function assigned for the Cortex-M33 */

/*!
 * @brief Select Digital mode.: Enable Digital mode. Digital input is enabled. */
#define PIO1_10_DIGIMODE_DIGITAL 0x01u
/*!
 * @brief Selects pin function.: Alternative connection 0. */
#define PIO1_10_FUNC_ALT0 0x00u
/*!
 * @brief Selects function mode (on-chip pull-up/pull-down resistor control).: Pull-up. Pull-up resistor enabled. */
#define PIO1_10_MODE_PULL_UP 0x02u
/*!
 * @brief Select Digital mode.: Enable Digital mode. Digital input is enabled. */
#define PIO1_14_DIGIMODE_DIGITAL 0x01u
/*!
 * @brief Selects pin function.: Alternative connection 0. */
#define PIO1_14_FUNC_ALT0 0x00u
/*!
 * @brief
 * Selects function mode (on-chip pull-up/pull-down resistor control).
 * : Pull-down.
 * Pull-down resistor enabled.
 */
#define PIO1_14_MODE_PULL_DOWN 0x01u
/*!
 * @brief Select Digital mode.: Enable Digital mode. Digital input is enabled. */
#define PIO1_17_DIGIMODE_DIGITAL 0x01u
/*!
 * @brief Selects pin function.: Alternative connection 0. */
#define PIO1_17_FUNC_ALT0 0x00u
/*!
 * @brief
 * Selects function mode (on-chip pull-up/pull-down resistor control).
 * : Pull-down.
 * Pull-down resistor enabled.
 */
#define PIO1_17_MODE_PULL_DOWN 0x01u
/*!
 * @brief Select Digital mode.: Enable Digital mode. Digital input is enabled. */
#define PIO1_21_DIGIMODE_DIGITAL 0x01u
/*!
 * @brief Selects pin function.: Alternative connection 0. */
#define PIO1_21_FUNC_ALT0 0x00u
/*!
 * @brief
 * Selects function mode (on-chip pull-up/pull-down resistor control).
 * : Pull-down.
 * Pull-down resistor enabled.
 */
#define PIO1_21_MODE_PULL_DOWN 0x01u
/*!
 * @brief Select Digital mode.: Enable Digital mode. Digital input is enabled. */
#define PIO1_23_DIGIMODE_DIGITAL 0x01u
/*!
 * @brief Selects pin function.: Alternative connection 0. */
#define PIO1_23_FUNC_ALT0 0x00u
/*!
 * @brief Selects function mode (on-chip pull-up/pull-down resistor control).: Pull-up. Pull-up resistor enabled. */
#define PIO1_23_MODE_PULL_UP 0x02u
/*!
 * @brief Controls open-drain mode.: Open-drain. Simulated open-drain output (high drive disabled). */
#define PIO1_23_OD_OPEN_DRAIN 0x01u
/*!
 * @brief Select Digital mode.: Enable Digital mode. Digital input is enabled. */
#define PIO1_5_DIGIMODE_DIGITAL 0x01u
/*!
 * @brief Selects pin function.: Alternative connection 0. */
#define PIO1_5_FUNC_ALT0 0x00u
/*!
 * @brief Selects function mode (on-chip pull-up/pull-down resistor control).: Pull-up. Pull-up resistor enabled. */
#define PIO1_5_MODE_PULL_UP 0x02u

/*! @name PIO1_5 (number 31), J8[1]/J9[18]/ARD_MIK_P1_5
  @{ */

/* Symbols to be used with GPIO driver */
/*!
 * @brief GPIO peripheral base pointer */
#define BOARD_INITINTERBUSPINS_GPIO_1_InterBus_ENB_GPIO GPIO
/*!
 * @brief GPIO pin mask */
#define BOARD_INITINTERBUSPINS_GPIO_1_InterBus_ENB_GPIO_PIN_MASK (1U << 5U)
/*!
 * @brief PORT peripheral base pointer */
#define BOARD_INITINTERBUSPINS_GPIO_1_InterBus_ENB_PORT 1U
/*!
 * @brief PORT pin number */
#define BOARD_INITINTERBUSPINS_GPIO_1_InterBus_ENB_PIN 5U
/*!
 * @brief PORT pin mask */
#define BOARD_INITINTERBUSPINS_GPIO_1_InterBus_ENB_PIN_MASK (1U << 5U)
/* @} */

/*! @name PIO1_10 (number 40), J12[4]/ARD_P1_10
  @{ */

/* Symbols to be used with GPIO driver */
/*!
 * @brief GPIO peripheral base pointer */
#define BOARD_INITINTERBUSPINS_GPIO_1_2_InterBus_PreENB_GPIO GPIO
/*!
 * @brief GPIO pin mask */
#define BOARD_INITINTERBUSPINS_GPIO_1_2_InterBus_PreENB_GPIO_PIN_MASK (1U << 10U)
/*!
 * @brief PORT peripheral base pointer */
#define BOARD_INITINTERBUSPINS_GPIO_1_2_InterBus_PreENB_PORT 1U
/*!
 * @brief PORT pin number */
#define BOARD_INITINTERBUSPINS_GPIO_1_2_InterBus_PreENB_PIN 10U
/*!
 * @brief PORT pin mask */
#define BOARD_INITINTERBUSPINS_GPIO_1_2_InterBus_PreENB_PIN_MASK (1U << 10U)
/* @} */

/*! @name PIO1_23 (number 42), J4[4]/U8[3]/J12[7]/HS_USB1_ID
  @{ */

/* Symbols to be used with GPIO driver */
/*!
 * @brief GPIO peripheral base pointer */
#define BOARD_INITINTERBUSPINS_GPIO_4_InterBus_FB_GPIO GPIO
/*!
 * @brief GPIO pin mask */
#define BOARD_INITINTERBUSPINS_GPIO_4_InterBus_FB_GPIO_PIN_MASK (1U << 23U)
/*!
 * @brief PORT peripheral base pointer */
#define BOARD_INITINTERBUSPINS_GPIO_4_InterBus_FB_PORT 1U
/*!
 * @brief PORT pin number */
#define BOARD_INITINTERBUSPINS_GPIO_4_InterBus_FB_PIN 23U
/*!
 * @brief PORT pin mask */
#define BOARD_INITINTERBUSPINS_GPIO_4_InterBus_FB_PIN_MASK (1U << 23U)
/* @} */

/*! @name PIO1_14 (number 57), J12[3]/EXP_P1_14
  @{ */

/* Symbols to be used with GPIO driver */
/*!
 * @brief GPIO peripheral base pointer */
#define BOARD_INITINTERBUSPINS_GPIO_0_2_InterBus_PreENA_GPIO GPIO
/*!
 * @brief GPIO pin mask */
#define BOARD_INITINTERBUSPINS_GPIO_0_2_InterBus_PreENA_GPIO_PIN_MASK (1U << 14U)
/*!
 * @brief PORT peripheral base pointer */
#define BOARD_INITINTERBUSPINS_GPIO_0_2_InterBus_PreENA_PORT 1U
/*!
 * @brief PORT pin number */
#define BOARD_INITINTERBUSPINS_GPIO_0_2_InterBus_PreENA_PIN 14U
/*!
 * @brief PORT pin mask */
#define BOARD_INITINTERBUSPINS_GPIO_0_2_InterBus_PreENA_PIN_MASK (1U << 14U)
/* @} */

/*! @name PIO1_21 (number 30), U12[6]/U13[3]/J8[6]/J9[4]/FC4_I2C_SDA
  @{ */

/* Symbols to be used with GPIO driver */
/*!
 * @brief GPIO peripheral base pointer */
#define BOARD_INITINTERBUSPINS_GPIO_0_InterBus_ENA_GPIO GPIO
/*!
 * @brief GPIO pin mask */
#define BOARD_INITINTERBUSPINS_GPIO_0_InterBus_ENA_GPIO_PIN_MASK (1U << 21U)
/*!
 * @brief PORT peripheral base pointer */
#define BOARD_INITINTERBUSPINS_GPIO_0_InterBus_ENA_PORT 1U
/*!
 * @brief PORT pin number */
#define BOARD_INITINTERBUSPINS_GPIO_0_InterBus_ENA_PIN 21U
/*!
 * @brief PORT pin mask */
#define BOARD_INITINTERBUSPINS_GPIO_0_InterBus_ENA_PIN_MASK (1U << 21U)
/* @} */

/*! @name PIO1_17 (number 43), J12[20]/J13[2]/EXP_P1_17
  @{ */

/* Symbols to be used with GPIO driver */
/*!
 * @brief GPIO peripheral base pointer */
#define BOARD_INITINTERBUSPINS_GPIO_3_InterBus_CLK_GPIO GPIO
/*!
 * @brief GPIO pin mask */
#define BOARD_INITINTERBUSPINS_GPIO_3_InterBus_CLK_GPIO_PIN_MASK (1U << 17U)
/*!
 * @brief PORT peripheral base pointer */
#define BOARD_INITINTERBUSPINS_GPIO_3_InterBus_CLK_PORT 1U
/*!
 * @brief PORT pin number */
#define BOARD_INITINTERBUSPINS_GPIO_3_InterBus_CLK_PIN 17U
/*!
 * @brief PORT pin mask */
#define BOARD_INITINTERBUSPINS_GPIO_3_InterBus_CLK_PIN_MASK (1U << 17U)
/* @} */

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_InitInterBusPins(void); /* Function assigned for the Cortex-M33 */

#if defined(__cplusplus)
}
#endif

/*!
 * @}
 */
#endif /* _PIN_MUX_H_ */

/***********************************************************************************************************************
 * EOF
 **********************************************************************************************************************/
